import {ExecutionStatus} from "../job-types.js";
import {compareIssues} from "./ReviewEvidenceValidator.js";
import {VerificationStatus, type ReviewEvidence, type ReviewIssue, type ReviewRule} from "./ReviewTypes.js";

const makeIssue=(ruleId:string,code:string,message:string,repairable:boolean,field?:string,path?:string):ReviewIssue=>({code,severity:"ERROR",message,ruleId,repairable,...(field?{field}:{}),...(path?{path}:{})});
const normalize=(path:string)=>path.replace(/\\/g,"/").replace(/^\.\//,"").replace(/\/+$/,"");
const within=(file:string,scope:string)=>file===scope||file.startsWith(`${scope}/`);

export const executionOutcomeRule:ReviewRule={id:"execution-outcome",evaluate(evidence){switch(evidence.executionStatus){case ExecutionStatus.COMPLETED:return [];case ExecutionStatus.FAILED:return [makeIssue(this.id,"EXECUTION_FAILED","Execution finished with FAILED status.",true,"executionStatus")];case ExecutionStatus.CANCELLED:return [makeIssue(this.id,"EXECUTION_CANCELLED","Cancelled execution cannot pass review.",true,"executionStatus")];default:return [makeIssue(this.id,"EXECUTION_INCOMPLETE","Execution has not reached a reviewable terminal status.",false,"executionStatus")];}}};
export const exitCodeRule:ReviewRule={id:"exit-code",evaluate(evidence){return evidence.exitCode===undefined||evidence.exitCode===null||evidence.exitCode===0?[]:[makeIssue(this.id,"NONZERO_EXIT_CODE",`Execution exited with code ${evidence.exitCode}.`,true,"exitCode")];}};
export const verificationRule:ReviewRule={id:"verification",evaluate(evidence){const verification=evidence.verification,optional=new Set(evidence.constraints?.optionalVerification??[]);return (["build","typecheck","tests"] as const).flatMap(field=>{const status=verification?.[field];if(optional.has(field))return [];if(status===VerificationStatus.PASS)return [];if(status===VerificationStatus.FAIL)return [makeIssue(this.id,`${field.toUpperCase()}_FAILED`,`${field} verification failed.`,true,`verification.${field}`)];if(status===VerificationStatus.UNKNOWN)return [makeIssue(this.id,`${field.toUpperCase()}_UNKNOWN`,`${field} verification is unknown.`,true,`verification.${field}`)];if(status===VerificationStatus.NOT_RUN)return [makeIssue(this.id,`${field.toUpperCase()}_NOT_RUN`,`${field} verification was not run.`,true,`verification.${field}`)];return [makeIssue(this.id,`${field.toUpperCase()}_MISSING`,`${field} verification is required but missing.`,true,`verification.${field}`)];});}};
export const scopeRule:ReviewRule={id:"scope",evaluate(evidence){const constraints=evidence.constraints;if(!constraints)return [];const allowed=(constraints.allowedPaths??[]).map(normalize),forbidden=(constraints.forbiddenPaths??[]).map(normalize),issues:ReviewIssue[]=[];for(const changed of (evidence.changedFiles??[]).map(normalize).sort()){if(allowed.length&&!allowed.some(scope=>within(changed,scope)))issues.push(makeIssue(this.id,"OUTSIDE_ALLOWED_SCOPE",`Changed file is outside the allowed scope: ${changed}.`,false,"changedFiles",changed));if(forbidden.some(scope=>within(changed,scope)))issues.push(makeIssue(this.id,"FORBIDDEN_PATH_CHANGED",`Changed forbidden file or path: ${changed}.`,false,"changedFiles",changed));}return issues.sort(compareIssues);}};
export const requiredArtifactRule:ReviewRule={id:"required-artifacts",evaluate(evidence){const constraints=evidence.constraints;if(!constraints?.requiredArtifacts)return [];const observed=new Set((constraints.observedArtifacts??[]).map(normalize));return constraints.requiredArtifacts.map(normalize).sort().filter(path=>!observed.has(path)).map(path=>makeIssue(this.id,"REQUIRED_ARTIFACT_MISSING",`Required artifact is missing: ${path}.`,true,"constraints.requiredArtifacts",path));}};
export const defaultReviewRules:readonly ReviewRule[]=[executionOutcomeRule,exitCodeRule,verificationRule,scopeRule,requiredArtifactRule];
