import {appendFile,mkdir,rm} from "node:fs/promises";
import {join} from "node:path";
import {randomUUID} from "node:crypto";
import {JobStore} from "./job-store.js";
import {ExecutionStatus,type JobRecord} from "./job-types.js";
import {AgentFactory} from "./runtime/AgentFactory.js";
import {AgentType} from "./runtime/AgentType.js";
import type {ExecutionHandle} from "./runtime/AgentRunner.js";
import {StreamingRuntime} from "./streaming/StreamingRuntime.js";
export class ExecutionError extends Error { constructor(public readonly code:"WORKTREE_REQUIRED"|"EXECUTION_ALREADY_RUNNING"|"EXECUTION_COMMAND_MISSING"|"EXECUTION_START_FAILED",message:string){super(message);this.name="ExecutionError"} }
export class ExecutionService { private readonly active=new Map<string,ExecutionHandle>();private readonly terminal=new Map<string,Promise<void>>();private readonly cancelling=new Set<string>();private readonly cancellation=new Map<string,Promise<boolean>>();constructor(private readonly jobs:JobStore,private readonly jobsRoot:string,private readonly agents=new AgentFactory(),readonly streaming=new StreamingRuntime()){} private log(job:JobRecord){return join(this.jobsRoot,job.jobId,"execution.log")}
 async start(job:JobRecord){if(!job.worktreePath)throw new ExecutionError("WORKTREE_REQUIRED","A prepared worktree is required.");if(this.active.has(job.jobId)||job.executionStatus===ExecutionStatus.RUNNING||job.executionStatus===ExecutionStatus.STARTING)throw new ExecutionError("EXECUTION_ALREADY_RUNNING","Job execution is already running.");const command=job.projectBinding?.commands[0];if(!command)throw new ExecutionError("EXECUTION_COMMAND_MISSING","No project execution command is configured.");const executionId=randomUUID(),startedAt=new Date().toISOString(),agentType=job.agentType??AgentType.CODEX;await mkdir(join(this.jobsRoot,job.jobId),{recursive:true});await this.jobs.appendLifecycleEvent(job.jobId,"JOB_STARTING","Starting job execution",{executionId,commandId:command.id});await this.jobs.setExecutionMetadata(job.jobId,{executionId,executionStatus:ExecutionStatus.STARTING,startedAt,finishedAt:undefined,exitCode:undefined});try{const runner=this.agents.getRunner(agentType),handle=await runner.run(job,async(stream,text)=>{this.streaming.publish({executionId,jobId:job.jobId,agentType,stream,text,timestamp:new Date().toISOString()});await appendFile(this.log(job),`[${stream}] ${text}`);await this.jobs.appendLifecycleEvent(job.jobId,"JOB_OUTPUT","Execution output",{stream,text:text.slice(0,4000)})});this.active.set(job.jobId,handle);await this.jobs.setExecutionMetadata(job.jobId,{executionId,executionStatus:ExecutionStatus.RUNNING,startedAt});await this.jobs.appendLifecycleEvent(job.jobId,"JOB_RUNNING","Job execution is running",{executionId});const completion = handle.completion.then(result=>this.finish(job.jobId,executionId,result.exitCode)).catch(error=>this.fail(job.jobId,executionId,error));this.terminal.set(job.jobId,completion);void completion.finally(()=>this.terminal.delete(job.jobId));return {executionId,status:ExecutionStatus.RUNNING,completion}}catch(error){await this.fail(job.jobId,executionId,error);throw new ExecutionError("EXECUTION_START_FAILED",error instanceof Error?error.message:"Execution failed to start.")}}
 async cancel(job:JobRecord){const existing=this.cancellation.get(job.jobId);if(existing)return existing;const running=this.active.get(job.jobId);if(!running)return false;this.cancelling.add(job.jobId);const completion=(async()=>{running.terminate();await (this.terminal.get(job.jobId)??running.completion).catch(()=>undefined);return true})();this.cancellation.set(job.jobId,completion);void completion.finally(()=>{this.cancellation.delete(job.jobId);this.cancelling.delete(job.jobId)});return completion}
 async cleanup(job:JobRecord){await this.cancel(job);this.active.delete(job.jobId);if(job.executionId)this.streaming.close(job.executionId);await rm(this.log(job),{force:true})}
 async getStatus(job:JobRecord){return {executionId:job.executionId,status:job.executionStatus??ExecutionStatus.NOT_STARTED,startedAt:job.startedAt,finishedAt:job.finishedAt,exitCode:job.exitCode}}
 private async finish(jobId:string,executionId:string,exitCode:number|null){this.active.delete(jobId);const current=await this.jobs.loadJob(jobId);this.streaming.close(executionId);const cancelled=this.cancelling.has(jobId)||current.executionStatus===ExecutionStatus.CANCELLED;const status=cancelled?ExecutionStatus.CANCELLED:exitCode===0?ExecutionStatus.COMPLETED:ExecutionStatus.FAILED,finishedAt=new Date().toISOString(),type=status===ExecutionStatus.COMPLETED?"JOB_COMPLETED":status===ExecutionStatus.CANCELLED?"JOB_CANCELLED":"JOB_FAILED" as const;await this.jobs.appendLifecycleEvent(jobId,type,status===ExecutionStatus.COMPLETED?"Job execution completed":status===ExecutionStatus.CANCELLED?"Job execution cancelled":"Job execution failed",{executionId,exitCode});await this.jobs.setExecutionMetadata(jobId,{executionId,executionStatus:status,startedAt:current.startedAt,finishedAt,exitCode:cancelled?(exitCode??null):exitCode})}
 private async fail(jobId:string,executionId:string,error:unknown){if(this.cancelling.has(jobId)){await this.finish(jobId,executionId,null);return}this.active.delete(jobId);const current=await this.jobs.loadJob(jobId);this.streaming.close(executionId);await this.jobs.appendLifecycleEvent(jobId,"JOB_FAILED","Job execution failed",{executionId,message:error instanceof Error?error.message:"Unknown error"});await this.jobs.setExecutionMetadata(jobId,{executionId,executionStatus:ExecutionStatus.FAILED,startedAt:current.startedAt,finishedAt:new Date().toISOString(),exitCode:null})}
 async markCancelled(jobId:string){const current=await this.jobs.loadJob(jobId);await this.jobs.setExecutionMetadata(jobId,{executionId:current.executionId,executionStatus:ExecutionStatus.CANCELLED,startedAt:current.startedAt,finishedAt:new Date().toISOString(),exitCode:current.exitCode??null});await this.jobs.appendLifecycleEvent(jobId,"JOB_CANCELLED","Job execution cancelled",{executionId:current.executionId});if(current.executionId)this.streaming.close(current.executionId)}
}
