import {mkdir,readFile,writeFile,rename,rm,stat,appendFile,truncate,open} from "node:fs/promises";
import {join} from "node:path"; import {randomUUID} from "node:crypto";
import {JobEvent,JobEventType,JobRecord,JobStatus,ALL_JOB_STATES,canTransitionJob} from "./job-types.js";
import {JobLock} from "./job-lock.js"; import {JobStoreError,JobStoreErrorCode} from "./errors.js";
export interface CreateJobInput {jobId:string;planId:string;projectId:string;maxFixRounds?:number;metadata?:Record<string,unknown>}
const bad=(c:JobStoreErrorCode,m:string):never=>{throw new JobStoreError(c,m)}; const iso=(x:unknown):x is string=>typeof x==="string"&&!Number.isNaN(Date.parse(x));
function record(x:unknown):asserts x is JobRecord {const v=x as Record<string,unknown>;if(!v||v.schemaVersion!=="1.0"||typeof v.jobId!=="string"||!v.jobId.trim()||typeof v.planId!=="string"||!v.planId.trim()||typeof v.projectId!=="string"||!v.projectId.trim()||!ALL_JOB_STATES.includes(v.state as JobStatus)||!Number.isInteger(v.fixRound)||!Number.isInteger(v.maxFixRounds)||Number(v.fixRound)<0||Number(v.maxFixRounds)<0||Number(v.maxFixRounds)>2||Number(v.fixRound)>Number(v.maxFixRounds)||!iso(v.createdAt)||!iso(v.updatedAt)||!Number.isInteger(v.lastEventSequence)||Number(v.lastEventSequence)<0)bad(JobStoreErrorCode.INVALID_JOB_RECORD,"Invalid job record")}
function event(x:unknown):asserts x is JobEvent {const v=x as Record<string,unknown>;if(!v||typeof v.eventId!=="string"||typeof v.jobId!=="string"||!Number.isInteger(v.sequence)||!ALL_JOB_STATES.includes(v.to as JobStatus)||(v.from!==null&&!ALL_JOB_STATES.includes(v.from as JobStatus))||!(["JOB_CREATED","JOB_STATE_CHANGED","FIX_ROUND_INCREMENTED"] as string[]).includes(String(v.type))||!iso(v.timestamp)||typeof v.reason!=="string"||!v.reason.trim())bad(JobStoreErrorCode.JOB_EVENT_LOG_CORRUPTED,"Invalid event")}
export class JobStore { constructor(private root:string){} private dir(id:string){return join(this.root,id)} private state(id:string){return join(this.dir(id),"job-state.json")} private log(id:string){return join(this.dir(id),"events.jsonl")} private lock(id:string){return join(this.dir(id),".job.lock")}
 async jobExists(id:string){try{await stat(this.dir(id));return true}catch(e){if((e as NodeJS.ErrnoException).code==="ENOENT")return false;throw e}}
 async createJob(i:CreateJobInput){if(!i.jobId?.trim()||!i.planId?.trim()||!i.projectId?.trim())bad(JobStoreErrorCode.INVALID_JOB_RECORD,"Required job fields missing");const max=i.maxFixRounds??2;if(!Number.isInteger(max)||max<0||max>2)bad(JobStoreErrorCode.INVALID_JOB_RECORD,"maxFixRounds must be 0..2");const d=this.dir(i.jobId);if(await this.jobExists(i.jobId))bad(JobStoreErrorCode.JOB_ALREADY_EXISTS,"Job already exists");await mkdir(d,{recursive:false});try{const t=new Date().toISOString();const e:JobEvent={eventId:randomUUID(),jobId:i.jobId,sequence:1,type:JobEventType.JOB_CREATED,from:null,to:JobStatus.DRAFT,timestamp:t,reason:"Job created"};const r:JobRecord={schemaVersion:"1.0",jobId:i.jobId,planId:i.planId,projectId:i.projectId,state:JobStatus.DRAFT,fixRound:0,maxFixRounds:max,createdAt:t,updatedAt:t,lastEventSequence:1,...(i.metadata?{metadata:i.metadata}:{})};await writeFile(this.log(i.jobId),JSON.stringify(e)+"\n");await this.atomic(this.state(i.jobId),r);return r}catch(e){await rm(d,{recursive:true,force:true});throw e}}
 async loadJob(id:string):Promise<JobRecord>{try{const x=JSON.parse(await readFile(this.state(id),"utf8"));record(x);return x}catch(e){if((e as NodeJS.ErrnoException).code==="ENOENT")bad(JobStoreErrorCode.JOB_NOT_FOUND,"Job not found");if(e instanceof JobStoreError)throw e;return bad(JobStoreErrorCode.JOB_STATE_CORRUPTED,"Corrupt job state")}}
 async listEvents(id:string){const r=await this.loadJob(id);let text="";try{text=await readFile(this.log(id),"utf8")}catch{bad(JobStoreErrorCode.JOB_EVENT_LOG_CORRUPTED,"Missing event log")}const es:JobEvent[]=[];for(const line of text.split(/\r?\n/).filter(Boolean)){try{const e=JSON.parse(line);event(e);es.push(e)}catch(e){if(e instanceof JobStoreError)throw e;bad(JobStoreErrorCode.JOB_EVENT_LOG_CORRUPTED,"Invalid event JSON")}}for(let n=0;n<es.length;n++){const e=es[n];if(e.jobId!==id||e.sequence!==n+1)bad(JobStoreErrorCode.JOB_EVENT_LOG_CORRUPTED,"Event sequence or jobId mismatch");if(n&&e.type===JobEventType.JOB_STATE_CHANGED&&!canTransitionJob(es[n-1].to,e.to))bad(JobStoreErrorCode.JOB_EVENT_LOG_CORRUPTED,"Invalid event transition")}if(es.length!==r.lastEventSequence||es.at(-1)?.to!==r.state)bad(JobStoreErrorCode.JOB_EVENT_LOG_CORRUPTED,"State and event log disagree");return es}
 async transitionJob(id:string,to:JobStatus,reason:string,metadata?:Record<string,unknown>){if(!reason?.trim())bad(JobStoreErrorCode.INVALID_TRANSITION,"Reason is required");const l=await JobLock.acquire(this.lock(id));try{const r=await this.loadJob(id);if(!ALL_JOB_STATES.includes(to)||!canTransitionJob(r.state,to))bad(JobStoreErrorCode.INVALID_TRANSITION,"Transition not allowed");const e=this.makeEvent(id,r.lastEventSequence+1,JobEventType.JOB_STATE_CHANGED,r.state,to,reason,metadata);const next={...r,state:to,updatedAt:e.timestamp,lastEventSequence:e.sequence};const size=(await stat(this.log(id))).size;await appendFile(this.log(id),JSON.stringify(e)+"\n");try{await this.atomic(this.state(id),next)}catch(x){try{await truncate(this.log(id),size)}catch{}throw x}return next}finally{await l.release()}}
 async cancelJob(id:string,reason:string){return this.transitionJob(id,JobStatus.CANCELLED,reason)}
 async incrementFixRound(id:string,reason:string){if(!reason?.trim())bad(JobStoreErrorCode.INVALID_TRANSITION,"Reason is required");const l=await JobLock.acquire(this.lock(id));try{const r=await this.loadJob(id);if(r.state!==JobStatus.AWAITING_REVIEW&&r.state!==JobStatus.FIXING)bad(JobStoreErrorCode.INVALID_TRANSITION,"Fix round not allowed");if(r.fixRound>=r.maxFixRounds)bad(JobStoreErrorCode.FIX_ROUND_LIMIT_EXCEEDED,"Maximum fix rounds reached");const e=this.makeEvent(id,r.lastEventSequence+1,JobEventType.FIX_ROUND_INCREMENTED,r.state,r.state,reason);const next={...r,fixRound:r.fixRound+1,updatedAt:e.timestamp,lastEventSequence:e.sequence};const size=(await stat(this.log(id))).size;await appendFile(this.log(id),JSON.stringify(e)+"\n");try{await this.atomic(this.state(id),next)}catch(x){try{await truncate(this.log(id),size)}catch{}throw x}return next}finally{await l.release()}}
 private makeEvent(id:string,n:number,type:JobEventType,from:JobStatus,to:JobStatus,reason:string,metadata?:Record<string,unknown>):JobEvent{return {eventId:randomUUID(),jobId:id,sequence:n,type,from,to,timestamp:new Date().toISOString(),reason:reason.trim(),...(metadata?{metadata}:{})}}
 private async atomic(path:string,value:unknown){const tmp=path+"."+randomUUID()+".tmp";try{const h=await open(tmp,"w");try{await h.writeFile(JSON.stringify(value,null,2)+"\n");await h.sync()}finally{await h.close()}await rename(tmp,path)}catch(e){try{await rm(tmp,{force:true})}catch{}throw e}}
}
