export const JobStatus = { DRAFT:"DRAFT", AWAITING_APPROVAL:"AWAITING_APPROVAL", QUEUED:"QUEUED", PREPARING:"PREPARING", RUNNING_AGENTS:"RUNNING_AGENTS", INTEGRATING:"INTEGRATING", TESTING:"TESTING", BUILDING_REVIEW_PACKAGE:"BUILDING_REVIEW_PACKAGE", AWAITING_REVIEW:"AWAITING_REVIEW", FIXING:"FIXING", COMPLETED:"COMPLETED", PAUSED:"PAUSED", FAILED:"FAILED", CANCELLED:"CANCELLED" } as const;
export type JobStatus = typeof JobStatus[keyof typeof JobStatus];
export const TERMINAL_JOB_STATES: ReadonlySet<JobStatus> = new Set([JobStatus.COMPLETED,JobStatus.FAILED,JobStatus.CANCELLED]);
const rules: Readonly<Record<JobStatus,readonly JobStatus[]>> = { DRAFT:["AWAITING_APPROVAL"],AWAITING_APPROVAL:["QUEUED","CANCELLED"],QUEUED:["PREPARING","CANCELLED"],PREPARING:["RUNNING_AGENTS","FAILED","CANCELLED","PAUSED"],RUNNING_AGENTS:["INTEGRATING","FAILED","CANCELLED","PAUSED"],INTEGRATING:["TESTING","FAILED","PAUSED","CANCELLED"],TESTING:["BUILDING_REVIEW_PACKAGE","FAILED","PAUSED","CANCELLED"],BUILDING_REVIEW_PACKAGE:["AWAITING_REVIEW","FAILED","PAUSED"],AWAITING_REVIEW:["COMPLETED","FIXING","PAUSED","FAILED","CANCELLED"],FIXING:["RUNNING_AGENTS","FAILED","PAUSED","CANCELLED"],PAUSED:["QUEUED","RUNNING_AGENTS","AWAITING_REVIEW","FAILED","CANCELLED"],COMPLETED:[],FAILED:[],CANCELLED:[] };
export const ALL_JOB_STATES = Object.values(JobStatus) as JobStatus[];
export const getAllowedTransitions = (s:JobStatus):JobStatus[] => [...(rules[s] ?? [])];
export const canTransitionJob = (from:JobStatus,to:JobStatus):boolean => from!==to && getAllowedTransitions(from).includes(to);
export const isTerminalJobState = (s:JobStatus):boolean => TERMINAL_JOB_STATES.has(s);
export interface JobProjectCommand { id:string; executable:string; args:string[]; timeoutSeconds:number; }
export interface JobProjectVerification { verifiedAt:string; configuredPath:string; canonicalPath:string; gitRoot:string; branch:string; headCommit:string; clean:true; commandsValid:true; originUrl?:string; }
export interface JobProjectBinding { schemaVersion:1; projectId:string; displayName:string; repositoryPath:string; defaultBranch:string; commands:JobProjectCommand[]; projectCreatedAt:string; projectUpdatedAt:string; boundAt:string; verification?:JobProjectVerification; }
import type {AgentType} from "./runtime/AgentType.js";
export const ExecutionStatus = { NOT_STARTED:"NOT_STARTED", STARTING:"STARTING", RUNNING:"RUNNING", COMPLETED:"COMPLETED", FAILED:"FAILED", CANCELLED:"CANCELLED" } as const;
export type ExecutionStatus = typeof ExecutionStatus[keyof typeof ExecutionStatus];
export interface JobRecord { schemaVersion:"1.0"; jobId:string; planId:string; projectId:string; state:JobStatus; fixRound:number; maxFixRounds:number; createdAt:string; updatedAt:string; lastEventSequence:number; pausedReason?:string; failure?:string; metadata?:Record<string,unknown>; projectBinding?:JobProjectBinding; agentType?:AgentType; worktreePath?:string; branchName?:string; worktreeCreatedAt?:string; executionId?:string; executionStatus?:ExecutionStatus; startedAt?:string; finishedAt?:string; exitCode?:number|null; }
export const JobEventType = { JOB_CREATED:"JOB_CREATED", JOB_PROJECT_BOUND:"JOB_PROJECT_BOUND", JOB_PROJECT_PREFLIGHT_PASSED:"JOB_PROJECT_PREFLIGHT_PASSED", JOB_PROJECT_PREFLIGHT_FAILED:"JOB_PROJECT_PREFLIGHT_FAILED", JOB_STATE_CHANGED:"JOB_STATE_CHANGED", FIX_ROUND_INCREMENTED:"FIX_ROUND_INCREMENTED", WORKTREE_CREATING:"WORKTREE_CREATING", WORKTREE_CREATED:"WORKTREE_CREATED", WORKTREE_FAILED:"WORKTREE_FAILED", WORKTREE_REMOVED:"WORKTREE_REMOVED", JOB_STARTING:"JOB_STARTING", JOB_RUNNING:"JOB_RUNNING", JOB_OUTPUT:"JOB_OUTPUT", JOB_COMPLETED:"JOB_COMPLETED", JOB_FAILED:"JOB_FAILED", JOB_CANCELLED:"JOB_CANCELLED" } as const;
export type JobEventType = typeof JobEventType[keyof typeof JobEventType];
export interface JobEvent { eventId:string; jobId:string; sequence:number; type:JobEventType; from:JobStatus|null; to:JobStatus; timestamp:string; reason:string; metadata?:Record<string,unknown>; }
