import {mkdir,readFile,writeFile,rename,rm,stat,appendFile,truncate,open,readdir} from "node:fs/promises";
import {join} from "node:path"; import {randomUUID} from "node:crypto";
import {JobEvent,JobEventType,JobProjectBinding,JobProjectVerification,JobRecord,JobStatus,ALL_JOB_STATES,canTransitionJob} from "./job-types.js"; import type {AgentType} from "./runtime/AgentType.js";
import {JobLock} from "./job-lock.js"; import {JobStoreError,JobStoreErrorCode} from "./errors.js";
import {retryTransientFilesystem} from "./transient-retry.js";
export interface CreateJobInput {jobId:string;planId:string;projectId:string;maxFixRounds?:number;metadata?:Record<string,unknown>;projectBinding?:JobProjectBinding;agentType?:AgentType}
const bad=(c:JobStoreErrorCode,m:string):never=>{throw new JobStoreError(c,m)}; const iso=(x:unknown):x is string=>typeof x==="string"&&!Number.isNaN(Date.parse(x));
const binding=(x:unknown):x is JobProjectBinding=>{const v=x as any;return !!v&&v.schemaVersion===1&&typeof v.projectId==="string"&&typeof v.displayName==="string"&&typeof v.repositoryPath==="string"&&typeof v.defaultBranch==="string"&&Array.isArray(v.commands)&&v.commands.every((c:any)=>c&&typeof c.id==="string"&&typeof c.executable==="string"&&Array.isArray(c.args)&&typeof c.timeoutSeconds==="number")&&iso(v.projectCreatedAt)&&iso(v.projectUpdatedAt)&&iso(v.boundAt)&&(!v.verification||!!v.verification&&iso(v.verification.verifiedAt)&&typeof v.verification.configuredPath==="string"&&typeof v.verification.canonicalPath==="string"&&typeof v.verification.gitRoot==="string"&&typeof v.verification.branch==="string"&&typeof v.verification.headCommit==="string"&&v.verification.clean===true&&v.verification.commandsValid===true)};
function record(x:unknown):asserts x is JobRecord {const v=x as Record<string,unknown>;if(!v||v.schemaVersion!=="1.0"||typeof v.jobId!=="string"||!v.jobId.trim()||typeof v.planId!=="string"||!v.planId.trim()||typeof v.projectId!=="string"||!v.projectId.trim()||!ALL_JOB_STATES.includes(v.state as JobStatus)||!Number.isInteger(v.fixRound)||!Number.isInteger(v.maxFixRounds)||Number(v.fixRound)<0||Number(v.maxFixRounds)<0||Number(v.maxFixRounds)>2||Number(v.fixRound)>Number(v.maxFixRounds)||!iso(v.createdAt)||!iso(v.updatedAt)||!Number.isInteger(v.lastEventSequence)||Number(v.lastEventSequence)<0)bad(JobStoreErrorCode.INVALID_JOB_RECORD,"Invalid job record");if("projectBinding" in v&&v.projectBinding!==undefined&&!binding(v.projectBinding))bad(JobStoreErrorCode.PROJECT_BINDING_CORRUPTED,"Invalid project binding")}
function event(x:unknown):asserts x is JobEvent {const v=x as Record<string,unknown>;if(!v||typeof v.eventId!=="string"||typeof v.jobId!=="string"||!Number.isInteger(v.sequence)||!ALL_JOB_STATES.includes(v.to as JobStatus)||(v.from!==null&&!ALL_JOB_STATES.includes(v.from as JobStatus))||!(Object.values(JobEventType) as string[]).includes(String(v.type))||!iso(v.timestamp)||typeof v.reason!=="string"||!v.reason.trim())bad(JobStoreErrorCode.JOB_EVENT_LOG_CORRUPTED,"Invalid event")}
const clone=<T>(x:T):T=>JSON.parse(JSON.stringify(x));
export class JobStore { constructor(private root:string){} private dir(id:string){return join(this.root,id)} private state(id:string){return join(this.dir(id),"job-state.json")} private log(id:string){return join(this.dir(id),"events.jsonl")} private lock(id:string){return join(this.dir(id),".job.lock")}
 async jobExists(id:string){try{await stat(this.dir(id));return true}catch(e){if((e as NodeJS.ErrnoException).code==="ENOENT")return false;throw e}}
 async createJob(i:CreateJobInput){if(!i.jobId?.trim()||!i.planId?.trim()||!i.projectId?.trim())bad(JobStoreErrorCode.INVALID_JOB_RECORD,"Required job fields missing");if(i.projectBinding&&!binding(i.projectBinding))bad(JobStoreErrorCode.INVALID_JOB_RECORD,"Invalid project binding");const max=i.maxFixRounds??2;if(!Number.isInteger(max)||max<0||max>2)bad(JobStoreErrorCode.INVALID_JOB_RECORD,"maxFixRounds must be 0..2");const d=this.dir(i.jobId);if(await this.jobExists(i.jobId))bad(JobStoreErrorCode.JOB_ALREADY_EXISTS,"Job already exists");await mkdir(d,{recursive:false});try{const t=new Date().toISOString(),e:JobEvent={eventId:randomUUID(),jobId:i.jobId,sequence:1,type:JobEventType.JOB_CREATED,from:null,to:JobStatus.DRAFT,timestamp:t,reason:"Job created"};const r:JobRecord={schemaVersion:"1.0",jobId:i.jobId,planId:i.planId,projectId:i.projectId,state:JobStatus.DRAFT,fixRound:0,maxFixRounds:max,createdAt:t,updatedAt:t,lastEventSequence:1,...(i.metadata?{metadata:clone(i.metadata)}:{}),...(i.projectBinding?{projectBinding:clone(i.projectBinding)}:{}),...(i.agentType?{agentType:i.agentType}:{})};await writeFile(this.log(i.jobId),JSON.stringify(e)+"\n");await this.atomic(this.state(i.jobId),r);if(i.projectBinding)await this.appendEventUnlocked(i.jobId,JobEventType.JOB_PROJECT_BOUND,"Project binding snapshot created",{projectId:i.projectBinding.projectId});return r}catch(e){await rm(d,{recursive:true,force:true});throw e}}
 async loadJob(id:string):Promise<JobRecord>{try{const x=JSON.parse(await readFile(this.state(id),"utf8"));record(x);return x}catch(e){if((e as NodeJS.ErrnoException).code==="ENOENT")bad(JobStoreErrorCode.JOB_NOT_FOUND,"Job not found");if(e instanceof JobStoreError)throw e;return bad(JobStoreErrorCode.JOB_STATE_CORRUPTED,"Corrupt job state")}}
 async listJobs():Promise<JobRecord[]>{let names:string[];try{names=await readdir(this.root)}catch(e){if((e as NodeJS.ErrnoException).code==="ENOENT")return [];throw e}const out:JobRecord[]=[];for(const n of names){if(n.startsWith("."))continue;const s=await stat(join(this.root,n));if(s.isDirectory())out.push(await this.loadJob(n))}return out.sort((a,b)=>a.jobId.localeCompare(b.jobId))}
 async findJobsByProjectId(projectId:string){return (await this.listJobs()).filter(j=>j.projectBinding?.projectId===projectId||(!j.projectBinding&&j.projectId===projectId))}
 async hasActiveJobsForProject(projectId:string){return (await this.findJobsByProjectId(projectId)).some(j=>!([JobStatus.COMPLETED,JobStatus.FAILED,JobStatus.CANCELLED] as JobStatus[]).includes(j.state))}
 async listEvents(id:string){const r=await this.loadJob(id);let text="";try{text=await readFile(this.log(id),"utf8")}catch{bad(JobStoreErrorCode.JOB_EVENT_LOG_CORRUPTED,"Missing event log")}const es:JobEvent[]=[];for(const line of text.split(/\r?\n/).filter(Boolean)){try{const e=JSON.parse(line);event(e);es.push(e)}catch(e){if(e instanceof JobStoreError)throw e;bad(JobStoreErrorCode.JOB_EVENT_LOG_CORRUPTED,"Invalid event JSON")}}for(let n=0;n<es.length;n++){const e=es[n];if(e.jobId!==id||e.sequence!==n+1)bad(JobStoreErrorCode.JOB_EVENT_LOG_CORRUPTED,"Event sequence or jobId mismatch");if(n&&e.type===JobEventType.JOB_STATE_CHANGED&&!canTransitionJob(es[n-1].to,e.to))bad(JobStoreErrorCode.JOB_EVENT_LOG_CORRUPTED,"Invalid event transition")}if(es.length!==r.lastEventSequence||es.at(-1)?.to!==r.state)bad(JobStoreErrorCode.JOB_EVENT_LOG_CORRUPTED,"State and event log disagree");return es}
 async appendProjectPreflightFailure(id:string,projectId:string,issueCodes:string[],checkedAt:string){const l=await JobLock.acquire(this.lock(id));try{await this.loadJob(id);return this.appendEventUnlocked(id,JobEventType.JOB_PROJECT_PREFLIGHT_FAILED,"Project preflight failed",{projectId,issueCodes:issueCodes.slice(0,20),checkedAt})}finally{await l.release()}}
 async persistVerification(id:string,verification:JobProjectVerification){const l=await JobLock.acquire(this.lock(id));try{const r=await this.loadJob(id);if(r.state!==JobStatus.AWAITING_APPROVAL)bad(JobStoreErrorCode.INVALID_TRANSITION,"Job is not awaiting approval");const e=this.makeEvent(id,r.lastEventSequence+1,JobEventType.JOB_PROJECT_PREFLIGHT_PASSED,r.state,r.state,"Project preflight passed",{projectId:r.projectBinding?.projectId,verifiedAt:verification.verifiedAt});const next={...r,projectBinding:{...r.projectBinding!,verification:clone(verification)},updatedAt:e.timestamp,lastEventSequence:e.sequence};await appendFile(this.log(id),JSON.stringify(e)+"\n");try{await this.atomic(this.state(id),next)}catch(x){try{await truncate(this.log(id),(await stat(this.log(id))).size-(JSON.stringify(e)+"\n").length)}catch{}throw x}return next}finally{await l.release()}}
 async setWorktreeMetadata(id:string,metadata:{worktreePath?:string;branchName?:string;worktreeCreatedAt?:string}){const l=await JobLock.acquire(this.lock(id));try{const r=await this.loadJob(id),next={...r,...metadata,updatedAt:new Date().toISOString()};if(!metadata.worktreePath){delete (next as any).worktreePath;delete (next as any).branchName;delete (next as any).worktreeCreatedAt}await this.atomic(this.state(id),next);return next}finally{await l.release()}}
 async setExecutionMetadata(id:string,metadata:{executionId?:string;executionStatus?:import("./job-types.js").ExecutionStatus;startedAt?:string;finishedAt?:string;exitCode?:number|null}){const l=await JobLock.acquire(this.lock(id));try{const r=await this.loadJob(id),next={...r,...metadata,updatedAt:new Date().toISOString()};await this.atomic(this.state(id),next);return next}finally{await l.release()}}
 async appendLifecycleEvent(id:string,type:JobEventType,reason:string,metadata?:Record<string,unknown>){const l=await JobLock.acquire(this.lock(id));try{return this.appendEventUnlocked(id,type,reason,metadata)}finally{await l.release()}}
 async transitionJob(id:string,to:JobStatus,reason:string,metadata?:Record<string,unknown>){if(!reason?.trim())bad(JobStoreErrorCode.INVALID_TRANSITION,"Reason is required");const l=await JobLock.acquire(this.lock(id));try{const r=await this.loadJob(id);if(!ALL_JOB_STATES.includes(to)||!canTransitionJob(r.state,to))bad(JobStoreErrorCode.INVALID_TRANSITION,"Transition not allowed");const e=this.makeEvent(id,r.lastEventSequence+1,JobEventType.JOB_STATE_CHANGED,r.state,to,reason,metadata);const next={...r,state:to,updatedAt:e.timestamp,lastEventSequence:e.sequence};const size=(await stat(this.log(id))).size;await appendFile(this.log(id),JSON.stringify(e)+"\n");try{await this.atomic(this.state(id),next)}catch(x){try{await truncate(this.log(id),size)}catch{}throw x}return next}finally{await l.release()}}
 async cancelJob(id:string,reason:string){return this.transitionJob(id,JobStatus.CANCELLED,reason)}
 async incrementFixRound(id:string,reason:string){if(!reason?.trim())bad(JobStoreErrorCode.INVALID_TRANSITION,"Reason is required");const l=await JobLock.acquire(this.lock(id));try{const r=await this.loadJob(id);if(r.state!==JobStatus.AWAITING_REVIEW&&r.state!==JobStatus.FIXING)bad(JobStoreErrorCode.INVALID_TRANSITION,"Fix round not allowed");if(r.fixRound>=r.maxFixRounds)bad(JobStoreErrorCode.FIX_ROUND_LIMIT_EXCEEDED,"Maximum fix rounds reached");const e=this.makeEvent(id,r.lastEventSequence+1,JobEventType.FIX_ROUND_INCREMENTED,r.state,r.state,reason);const next={...r,fixRound:r.fixRound+1,updatedAt:e.timestamp,lastEventSequence:e.sequence};const size=(await stat(this.log(id))).size;await appendFile(this.log(id),JSON.stringify(e)+"\n");try{await this.atomic(this.state(id),next)}catch(x){try{await truncate(this.log(id),size)}catch{}throw x}return next}finally{await l.release()}}
 private async appendEventUnlocked(id:string,type:JobEventType,reason:string,metadata?:Record<string,unknown>){const r=await this.loadJob(id),e=this.makeEvent(id,r.lastEventSequence+1,type,r.state,r.state,reason,metadata);const next={...r,updatedAt:e.timestamp,lastEventSequence:e.sequence};await appendFile(this.log(id),JSON.stringify(e)+"\n");try{await this.atomic(this.state(id),next)}catch(x){try{await truncate(this.log(id),(await stat(this.log(id))).size-(JSON.stringify(e)+"\n").length)}catch{}throw x}return next}
 private makeEvent(id:string,n:number,type:JobEventType,from:JobStatus,to:JobStatus,reason:string,metadata?:Record<string,unknown>):JobEvent{return {eventId:randomUUID(),jobId:id,sequence:n,type,from,to,timestamp:new Date().toISOString(),reason:reason.trim(),...(metadata?{metadata}:{})}}
 private async atomic(path:string,value:unknown){const tmp=path+"."+randomUUID()+".tmp";try{const h=await open(tmp,"w");try{await h.writeFile(JSON.stringify(value,null,2)+"\n");await h.sync()}finally{await h.close()}await retryTransientFilesystem(()=>rename(tmp,path))}catch(e){try{await retryTransientFilesystem(()=>rm(tmp,{force:true}))}catch{}throw e}}
}
