import {access,mkdir,rm} from "node:fs/promises";
import {dirname,resolve} from "node:path";
import {GitService} from "./git-service.js";
import type {JobRecord} from "./job-types.js";
import {retryTransientFilesystem} from "./transient-retry.js";
export class WorktreeError extends Error { constructor(public readonly code:"WORKTREE_EXISTS"|"WORKTREE_FAILED",message:string){super(message);this.name="WorktreeError"} }
export interface WorktreeResult {path:string;branchName:string;createdAt:string}
export class WorktreeService { constructor(private readonly runtimeRoot:string,private readonly git=new GitService()){} getPath(job:Pick<JobRecord,"jobId">){return resolve(this.runtimeRoot,"worktrees",job.jobId)} getBranchName(job:Pick<JobRecord,"jobId">){return `job/${job.jobId}`}
 async exists(job:Pick<JobRecord,"jobId">){try{await access(this.getPath(job));return true}catch(e){if((e as NodeJS.ErrnoException).code==="ENOENT")return false;throw e}}
async createWorktree(job:JobRecord):Promise<WorktreeResult>{const verification=job.projectBinding?.verification;if(!verification)throw new WorktreeError("WORKTREE_FAILED","Project has not been verified.");const path=this.getPath(job),branchName=this.getBranchName(job);if(await this.exists(job))throw new WorktreeError("WORKTREE_EXISTS","Worktree already exists.");let branchCreated=false;try{await mkdir(dirname(path),{recursive:true});await this.git.branch(verification.gitRoot,branchName,job.projectBinding!.defaultBranch);branchCreated=true;await this.git.worktreeAdd(verification.gitRoot,path,branchName);return {path,branchName,createdAt:new Date().toISOString()}}catch(e){await retryTransientFilesystem(()=>rm(path,{recursive:true,force:true})).catch(()=>undefined);if(branchCreated)await this.git.branchDelete(verification.gitRoot,branchName).catch(()=>undefined);if(e instanceof WorktreeError)throw e;throw new WorktreeError("WORKTREE_FAILED",e instanceof Error?e.message:"Git worktree creation failed.")}}
async removeWorktree(job:JobRecord){const verification=job.projectBinding?.verification,path=job.worktreePath??this.getPath(job);if(!verification)return;try{if(await this.exists({jobId:job.jobId}))await this.git.worktreeRemove(verification.gitRoot,path)}finally{await retryTransientFilesystem(()=>rm(path,{recursive:true,force:true})).catch(()=>undefined)}}
 async cleanup(job:JobRecord){await this.removeWorktree(job);const verification=job.projectBinding?.verification,branch=job.branchName??this.getBranchName(job);if(verification&&await this.git.branchExists(verification.gitRoot,branch))await this.git.branchDelete(verification.gitRoot,branch)}
}
