import { describe, expect, it } from "vitest";
import { WORKFLOW_PLAN_LIMITS, WORKFLOW_PLAN_VERSION, WorkflowAgentType, normalizeWorkflowPlan, validateWorkflowPlan } from "../src/index.js";

const valid = () => ({ workflowVersion: WORKFLOW_PLAN_VERSION, projectId: "revit-addin-solution", goal: "Inspect and improve Tag Arranger", tasks: [{ taskId: "implementation", agentType: WorkflowAgentType.CODEX, instruction: "Inspect Tag Arranger and implement the smallest required fix.", dependsOn: [], verification: { requiredCommandIds: ["build"], expectedArtifacts: ["src/TagArranger.cs"] } }, { taskId: "verification", agentType: WorkflowAgentType.ANTIGRAVITY, instruction: "Review the implementation and verify integration risks.", dependsOn: ["implementation"] }] });
const invalid = (plan: unknown, code: string) => expect(validateWorkflowPlan(plan)).toMatchObject({ success: false, errors: expect.arrayContaining([expect.objectContaining({ code })]) });

describe("WorkflowPlan v1", () => {
    it("validates a single task and a CODEX to ANTIGRAVITY workflow", () => { const single = valid(); single.tasks.splice(1); expect(validateWorkflowPlan(single)).toMatchObject({ success: true }); expect(validateWorkflowPlan(valid())).toMatchObject({ success: true }); });
    it("normalizes independent tasks, dependencies, commands, and artifacts deterministically", () => { const plan = valid(); plan.tasks.reverse(); plan.tasks[1].dependsOn = ["implementation"]; plan.tasks[1].verification = { requiredCommandIds: ["test", "build"], expectedArtifacts: ["src/z.ts", "src/a.ts"] }; const a = normalizeWorkflowPlan(plan), b = normalizeWorkflowPlan(JSON.parse(JSON.stringify(plan))); expect(a).toEqual(b); expect(a.tasks.map(task => task.taskId)).toEqual(["implementation", "verification"]); expect(plan.tasks[0].taskId).toBe("verification"); });
    it("rejects unsafe project IDs and unsupported agents", () => { for (const projectId of ["../foo", "C:\\foo", "/foo", ""]) invalid({ ...valid(), projectId }, "INVALID_PROJECT_ID"); invalid({ ...valid(), tasks: [{ ...valid().tasks[0], agentType: "OTHER" }] }, "INVALID_AGENT"); });
    it("rejects duplicate, self, unknown, direct, and indirect dependencies", () => { invalid({ ...valid(), tasks: [{ ...valid().tasks[0] }, { ...valid().tasks[0] }] }, "DUPLICATE_TASK_ID"); invalid({ ...valid(), tasks: [{ ...valid().tasks[0], dependsOn: ["implementation"] }] }, "SELF_DEPENDENCY"); invalid({ ...valid(), tasks: [{ ...valid().tasks[0], dependsOn: ["missing"] }] }, "UNKNOWN_DEPENDENCY"); invalid({ ...valid(), tasks: [{ ...valid().tasks[0], taskId: "a", dependsOn: ["b"] }, { ...valid().tasks[1], taskId: "b", dependsOn: ["a"] }] }, "DEPENDENCY_CYCLE"); invalid({ ...valid(), tasks: [{ ...valid().tasks[0], taskId: "a", dependsOn: ["b"] }, { ...valid().tasks[1], taskId: "b", dependsOn: ["c"] }, { ...valid().tasks[1], taskId: "c", dependsOn: ["a"] }] }, "DEPENDENCY_CYCLE"); });
    it("rejects unsafe artifacts and command payloads", () => { for (const path of ["../secret.txt", "C:\\Users\\x", "/etc/passwd"]) invalid({ ...valid(), tasks: [{ ...valid().tasks[0], verification: { expectedArtifacts: [path] } }] }, "INVALID_ARTIFACT_PATH"); invalid({ ...valid(), tasks: [{ ...valid().tasks[0], verification: { requiredCommandIds: ["build", "../shell"] } }] }, "INVALID_COMMAND_ID"); invalid({ ...valid(), executable: "powershell.exe" }, "INVALID_WORKFLOW"); });
    it("enforces explicit plan bounds", () => { invalid({ ...valid(), tasks: Array.from({ length: WORKFLOW_PLAN_LIMITS.tasks + 1 }, (_, i) => ({ ...valid().tasks[0], taskId: `task-${i}` })) }, "EMPTY_TASKS"); invalid({ ...valid(), goal: "x".repeat(WORKFLOW_PLAN_LIMITS.goalLength + 1) }, "EMPTY_GOAL"); invalid({ ...valid(), tasks: [{ ...valid().tasks[0], instruction: "x".repeat(WORKFLOW_PLAN_LIMITS.instructionLength + 1) }] }, "EMPTY_INSTRUCTION"); invalid({ ...valid(), tasks: [{ ...valid().tasks[0], dependsOn: Array.from({ length: WORKFLOW_PLAN_LIMITS.dependenciesPerTask + 1 }, () => "x") }] }, "INVALID_WORKFLOW"); });
    it("round-trips clean JSON and rejects unknown versions", () => { const input = JSON.parse(JSON.stringify(valid())); const result = validateWorkflowPlan(input); expect(result).toMatchObject({ success: true }); if (result.success) expect(JSON.parse(JSON.stringify(result.data))).toEqual(result.data); invalid({ ...valid(), workflowVersion: 2 }, "INVALID_VERSION"); });
});
