import { afterEach, describe, expect, it } from 'vitest';
import { execFileSync } from 'node:child_process';
import { access, mkdtemp, mkdir, rm, writeFile, unlink } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { buildBridgeApp } from '../src/app.js';
const dirs:string[]=[]; const apps:any[]=[]; const h={authorization:'Bearer phase5-token'};
const plan=(projectId:string,planId='PLAN-phase5-1')=>({schemaVersion:'1.0',planId,projectId,objective:'A sufficiently long Phase 5 objective',baseBranch:'main',tasks:[{taskId:'task-1',agent:'codex',title:'Review',instructions:'Review the requested change safely.',allowedPaths:['src']}],acceptanceCriteria:['works'],testCommands:[],screenshotsRequired:[],limits:{maxFixRounds:2,agentTimeoutMinutes:45,jobTimeoutMinutes:120,maxChangedFilesPerAgent:30,maxCommandsPerAgent:80}});
const setup=async()=>{const root=await mkdtemp(join(tmpdir(),'phase5-'));dirs.push(root);const repo=join(root,'repo');await mkdir(repo);execFileSync('git',['init','-b','main'],{cwd:repo});execFileSync('git',['config','user.name','Phase 5 Test'],{cwd:repo});execFileSync('git',['config','user.email','phase5@example.com'],{cwd:repo});await writeFile(join(repo,'README.md'),'clean');execFileSync('git',['add','.'],{cwd:repo});execFileSync('git',['commit','-m','initial'],{cwd:repo});const app=buildBridgeApp({runtimeRootDirectory:join(root,'runtime'),authToken:'phase5-token',allowedProjectRoots:[root],generateJobId:()=>`JOB-${Math.random().toString(16).slice(2)}`});apps.push(app);const payload={projectId:'phase5-project',displayName:'Phase 5',repositoryPath:repo,defaultBranch:'main',commands:[{id:'test',executable:'pnpm',args:['test'],timeoutSeconds:30}]};const registered=await app.inject({method:'POST',url:'/api/projects',headers:h,payload});expect(registered.statusCode).toBe(201);return {app,repo};};
const post=(app:any,url:string,payload?:unknown)=>app.inject({method:'POST',url,headers:h,payload});
afterEach(async()=>{for(const a of apps)await a.close();apps.length=0;while(dirs.length)await rm(dirs.pop()!,{recursive:true,force:true})});
describe('Phase 5A project-aware jobs',()=>{
 it('rejects an unregistered project without creating a partial job',async()=>{const {app}=await setup();const response=await post(app,'/api/jobs',plan('unregistered-project','PLAN-phase5-missing'));expect(response.statusCode).toBe(404);expect(response.json().error.code).toBe('PROJECT_NOT_FOUND');await expect(access(join(dirs[0],'runtime','jobs'))).rejects.toThrow();});
 it('binds a registered project and approves only after clean preflight',async()=>{const {app}=await setup();const created=await post(app,'/api/jobs',plan('phase5-project'));expect(created.statusCode).toBe(201);const data=created.json().data;expect(data.job.projectBinding.projectId).toBe(data.plan.projectId);expect(data.job.projectBinding.projectUpdatedAt).toBeTruthy();const approved=await post(app,`/api/jobs/${data.job.jobId}/approve`,{reason:'Approve clean repository'});expect(approved.statusCode).toBe(200);expect(approved.json().data.job.state).toBe('QUEUED');expect(approved.json().data.verification.headCommit).toMatch(/^[0-9a-f]{40}$/);const events=(await app.inject({method:'GET',url:`/api/jobs/${data.job.jobId}/events`,headers:h})).json().data.events;expect(events.map((e:any)=>e.type)).toContain('JOB_PROJECT_BOUND');expect(events.map((e:any)=>e.type)).toContain('JOB_PROJECT_PREFLIGHT_PASSED');});
 it('rejects dirty approval and keeps awaiting approval',async()=>{const {app,repo}=await setup();const created=await post(app,'/api/jobs',plan('phase5-project','PLAN-phase5-dirty'));const id=created.json().data.job.jobId;await writeFile(join(repo,'untracked.txt'),'dirty');const rejected=await post(app,`/api/jobs/${id}/approve`);expect(rejected.statusCode).toBe(409);const body=rejected.json();expect(body.error.code).toBe('PROJECT_PREFLIGHT_FAILED');expect(body.error.details.preflight.issues.map((x:any)=>x.code)).toContain('WORKING_TREE_DIRTY');expect((await app.inject({method:'GET',url:`/api/jobs/${id}`,headers:h})).json().data.job.state).toBe('AWAITING_APPROVAL');const events=(await app.inject({method:'GET',url:`/api/jobs/${id}/events`,headers:h})).json().data.events;expect(events.map((e:any)=>e.type)).toContain('JOB_PROJECT_PREFLIGHT_FAILED');await unlink(join(repo,'untracked.txt'));});
 it('detects configuration changes and guards deletion',async()=>{const {app,repo}=await setup();const created=await post(app,'/api/jobs',plan('phase5-project','PLAN-phase5-change'));const id=created.json().data.job.jobId;const update=await app.inject({method:'PUT',url:'/api/projects/phase5-project',headers:h,payload:{displayName:'Changed',repositoryPath:repo,defaultBranch:'main',commands:[{id:'test',executable:'pnpm',args:['test'],timeoutSeconds:30}]}});expect(update.statusCode).toBe(200);const rejected=await post(app,`/api/jobs/${id}/approve`);expect(rejected.statusCode).toBe(409);expect(rejected.json().error.code).toBe('PROJECT_CONFIGURATION_CHANGED');const del=await app.inject({method:'DELETE',url:'/api/projects/phase5-project',headers:h});expect(del.statusCode).toBe(409);expect(del.json().error.code).toBe('PROJECT_IN_USE');await post(app,`/api/jobs/${id}/cancel`,{reason:'Cancel stale job'});expect((await app.inject({method:'DELETE',url:'/api/projects/phase5-project',headers:h})).statusCode).toBe(200);});
});


