import { mkdir } from "node:fs/promises";
import { join } from "node:path";
import { AgentType, ExecutionError, ExecutionService, JobStore, WorktreeError, WorktreeService, type JobEvent, type JobProjectBinding, type JobProjectVerification } from '@local-orchestrator/orchestrator';
import { validatePlan } from '@local-orchestrator/contracts';
import { ProjectError, ProjectRegistry, ProjectPreflightService, type ProjectDefinition } from '@local-orchestrator/projects';
import { ApiError } from '../errors/api-error.js';
import { assertValidJobId, generateJobId } from './job-id.js';
import { PlanStore } from './plan-store.js';
const clone=<T>(x:T):T=>JSON.parse(JSON.stringify(x));
const stableCommands=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b);
const safePreflight=(p:any)=>({projectId:p.projectId,checkedAt:p.checkedAt,ok:p.ok,repository:{exists:p.repository.exists,isDirectory:p.repository.isDirectory,isGitRepository:p.repository.isGitRepository},git:{root:p.git.root,branch:p.git.branch,detachedHead:p.git.detachedHead,headCommit:p.git.headCommit,clean:p.git.clean,changedFiles:p.git.changedFiles.slice(0,100)},policy:{defaultBranch:p.policy.defaultBranch,branchMatches:p.policy.branchMatches,commandsValid:p.policy.commandsValid},issues:p.issues.map((i:any)=>({code:i.code,severity:i.severity,message:i.message}))});
export class BridgeJobService {
 constructor(private jobs:JobStore,private plans:PlanStore,private jobsRoot:string,private registry:ProjectRegistry,private preflight:ProjectPreflightService,private ids=generateJobId,private worktrees=new WorktreeService(join(jobsRoot,'..')),private executions=new ExecutionService(jobs,jobsRoot)){}
 async createJobFromPlan(input:unknown){const v=validatePlan(input);if(!v.success)throw new ApiError('PLAN_VALIDATION_FAILED','The submitted plan is invalid.',400,{issues:v.issues});const p=v.data;let project:ProjectDefinition;try{project=await this.registry.getProject(p.projectId)}catch(e){throw e}const id=this.ids();assertValidJobId(id);await mkdir(this.jobsRoot,{recursive:true});const b:JobProjectBinding={schemaVersion:1,projectId:project.projectId,displayName:project.displayName,repositoryPath:project.repositoryPath,defaultBranch:project.defaultBranch,commands:clone(project.commands),projectCreatedAt:project.createdAt,projectUpdatedAt:project.updatedAt,boundAt:new Date().toISOString()};const agentType=p.tasks[0]?.agent==='antigravity'?AgentType.ANTIGRAVITY:AgentType.CODEX;try{await this.plans.savePlan(id,p);const created=await this.jobs.createJob({jobId:id,planId:p.planId,projectId:p.projectId,maxFixRounds:p.limits.maxFixRounds,projectBinding:b,agentType});const job=await this.jobs.transitionJob(id,'AWAITING_APPROVAL','Plan submitted for user approval');return {job,plan:p};}catch(e){await this.plans.deletePlan(id);throw e;}}
 async getJobDetails(id:string){assertValidJobId(id);const j=await this.jobs.loadJob(id),p=await this.plans.loadPlan(id);if(p.planId!==j.planId||p.projectId!==j.projectId)throw new ApiError('JOB_DATA_INCONSISTENT','Job data is inconsistent.',500);return {job:j,plan:p};}
 async approveJob(id:string,reason:string){assertValidJobId(id);const j=await this.jobs.loadJob(id);if(!j.projectBinding)throw new ApiError('PROJECT_BINDING_MISSING','The job has no project binding snapshot.',409);if(j.projectBinding.projectId!==j.projectId)throw new ApiError('PROJECT_BINDING_CORRUPTED','The job project binding is invalid.',500);let project:ProjectDefinition;try{project=await this.registry.getProject(j.projectBinding.projectId)}catch(e){throw e}if(project.updatedAt!==j.projectBinding.projectUpdatedAt||project.repositoryPath!==j.projectBinding.repositoryPath||project.defaultBranch!==j.projectBinding.defaultBranch||project.displayName!==j.projectBinding.displayName||!stableCommands(project.commands,j.projectBinding.commands))throw new ApiError('PROJECT_CONFIGURATION_CHANGED','The project configuration changed after this job was created.',409,{projectId:j.projectBinding.projectId});const result=await this.preflight.runPreflight(project);if(!result.ok){await this.jobs.appendProjectPreflightFailure(id,project.projectId,result.issues.filter(x=>x.severity==='error').map(x=>x.code),result.checkedAt);throw new ApiError('PROJECT_PREFLIGHT_FAILED','Project repository is not ready for job approval.',409,{projectId:project.projectId,preflight:safePreflight(result)});}const v:JobProjectVerification={verifiedAt:result.checkedAt,configuredPath:result.repository.configuredPath,canonicalPath:result.repository.canonicalPath!,gitRoot:result.git.root!,branch:result.git.branch!,headCommit:result.git.headCommit!,clean:true,commandsValid:true,...(result.git.originUrl?{originUrl:result.git.originUrl}:{})};await this.jobs.persistVerification(id,v);return {job:await this.jobs.transitionJob(id,'QUEUED',reason),verification:v};}
 async cancelJob(id:string,reason:string){assertValidJobId(id);const job=await this.jobs.loadJob(id);if(job.executionStatus==='RUNNING'||job.executionStatus==='STARTING'){await this.executions.markCancelled(id);await this.executions.cancel(job)}return {job:await this.jobs.cancelJob(id,reason)}}
 async getJobEvents(id:string):Promise<{jobId:string;events:JobEvent[]}>{assertValidJobId(id);return {jobId:id,events:await this.jobs.listEvents(id)}}
 async prepareJob(id:string){assertValidJobId(id);const job=await this.jobs.loadJob(id);if(job.state!=='QUEUED'||!job.projectBinding?.verification)throw new ApiError('APPROVAL_REQUIRED','Job approval and project verification are required before preparation.',409);if(job.worktreePath||await this.worktrees.exists(job))throw new ApiError('WORKTREE_EXISTS','A worktree already exists for this job.',409);await this.jobs.appendLifecycleEvent(id,'WORKTREE_CREATING','Creating job worktree');try{const created=await this.worktrees.createWorktree(job);const saved=await this.jobs.setWorktreeMetadata(id,{worktreePath:created.path,branchName:created.branchName,worktreeCreatedAt:created.createdAt});await this.jobs.appendLifecycleEvent(id,'WORKTREE_CREATED','Job worktree created',{path:created.path,branchName:created.branchName});return {job:saved,worktree:created}}catch(e){await this.jobs.appendLifecycleEvent(id,'WORKTREE_FAILED','Job worktree creation failed',{message:e instanceof Error?e.message:'Unknown error'});if(e instanceof WorktreeError)throw new ApiError(e.code,e.message,e.code==='WORKTREE_EXISTS'?409:500);throw e}}
 async startJob(id:string){assertValidJobId(id);const job=await this.jobs.loadJob(id);try{const execution=await this.executions.start(job);return {job:await this.jobs.loadJob(id),execution}}catch(e){if(e instanceof ExecutionError)throw new ApiError(e.code,e.message,e.code==='EXECUTION_ALREADY_RUNNING'?409: e.code==='WORKTREE_REQUIRED'?409:400);throw e}}
 async cleanupJobWorktree(id:string){assertValidJobId(id);const job=await this.jobs.loadJob(id);await this.worktrees.cleanup(job);const saved=await this.jobs.setWorktreeMetadata(id,{});await this.jobs.appendLifecycleEvent(id,'WORKTREE_REMOVED','Job worktree removed');return {job:saved}}
 async deleteProject(id:string){const active=(await this.jobs.findJobsByProjectId(id)).filter(j=>!['COMPLETED','FAILED','CANCELLED'].includes(j.state));if(active.length)throw new ApiError('PROJECT_IN_USE','The project is referenced by active jobs.',409,{projectId:id,activeJobCount:active.length,jobIds:active.slice(0,20).map(j=>j.jobId)});await this.registry.deleteProject(id);}
}
