import {ScheduledTaskStatus,type ScheduledTask,type ScheduledTaskDefinition,type SchedulerResult} from "./SchedulerTypes.js";
export class SchedulerPlanError extends Error { constructor(public readonly code:"DUPLICATE_TASK_ID"|"UNKNOWN_DEPENDENCY"|"SELF_DEPENDENCY"|"DEPENDENCY_CYCLE"|"INVALID_TASK_TRANSITION",message:string){super(message);this.name="SchedulerPlanError"} }
const terminal=new Set<ScheduledTaskStatus>([ScheduledTaskStatus.COMPLETED,ScheduledTaskStatus.FAILED,ScheduledTaskStatus.CANCELLED,ScheduledTaskStatus.BLOCKED]);
const clone=(task:ScheduledTask):ScheduledTask=>({...task,dependencies:[...task.dependencies]});
export class SchedulerPlan { private readonly tasks=new Map<string,ScheduledTask>(); constructor(definitions:ScheduledTaskDefinition[]){this.validate(definitions);for(const definition of definitions){this.tasks.set(definition.taskId,{taskId:definition.taskId,jobId:definition.jobId,agentType:definition.agentType,dependencies:[...(definition.dependencies??[])].sort(),status:ScheduledTaskStatus.PENDING})}this.refresh()}
 private validate(definitions:ScheduledTaskDefinition[]){const ids=new Set<string>();for(const task of definitions){if(!task.taskId?.trim()||ids.has(task.taskId))throw new SchedulerPlanError("DUPLICATE_TASK_ID",`Duplicate or invalid task ID: ${task.taskId}`);ids.add(task.taskId)}for(const task of definitions){for(const dependency of task.dependencies??[]){if(dependency===task.taskId)throw new SchedulerPlanError("SELF_DEPENDENCY",`Task ${task.taskId} depends on itself.`);if(!ids.has(dependency))throw new SchedulerPlanError("UNKNOWN_DEPENDENCY",`Task ${task.taskId} depends on unknown task ${dependency}.`)}}const visited=new Set<string>(),visiting=new Set<string>();const byId=new Map(definitions.map(task=>[task.taskId,task]));const visit=(id:string)=>{if(visiting.has(id))throw new SchedulerPlanError("DEPENDENCY_CYCLE",`Dependency cycle includes ${id}.`);if(visited.has(id))return;visiting.add(id);for(const dependency of [...(byId.get(id)?.dependencies??[])].sort())visit(dependency);visiting.delete(id);visited.add(id)};for(const id of [...ids].sort())visit(id)}
 private refresh(){let changed=true;while(changed){changed=false;for(const task of this.sorted()){if(task.status!==ScheduledTaskStatus.PENDING&&task.status!==ScheduledTaskStatus.READY)continue;const previous=task.status,dependencies=task.dependencies.map(id=>this.tasks.get(id)!);if(dependencies.some(x=>x.status===ScheduledTaskStatus.FAILED||x.status===ScheduledTaskStatus.CANCELLED||x.status===ScheduledTaskStatus.BLOCKED)){task.status=ScheduledTaskStatus.BLOCKED}else if(dependencies.every(x=>x.status===ScheduledTaskStatus.COMPLETED)){task.status=ScheduledTaskStatus.READY}else{task.status=ScheduledTaskStatus.PENDING}if(previous!==task.status)changed=true}}}
 private sorted(){return [...this.tasks.values()].sort((a,b)=>a.taskId.localeCompare(b.taskId))}
 getTask(taskId:string){const task=this.tasks.get(taskId);if(!task)throw new SchedulerPlanError("UNKNOWN_DEPENDENCY",`Unknown task ${taskId}.`);return clone(task)}
 getTasks(){return this.sorted().map(clone)}
 getReadyTasks(){this.refresh();return this.sorted().filter(task=>task.status===ScheduledTaskStatus.READY).map(clone)}
 start(taskId:string){const task=this.tasks.get(taskId);if(!task||task.status!==ScheduledTaskStatus.READY)throw new SchedulerPlanError("INVALID_TASK_TRANSITION",`Task ${taskId} is not ready.`);task.status=ScheduledTaskStatus.RUNNING;return clone(task)}
 complete(taskId:string){return this.transitionRunning(taskId,ScheduledTaskStatus.COMPLETED)}
 fail(taskId:string){return this.transitionRunning(taskId,ScheduledTaskStatus.FAILED)}
 cancel(taskId:string){const task=this.tasks.get(taskId);if(!task||terminal.has(task.status))throw new SchedulerPlanError("INVALID_TASK_TRANSITION",`Task ${taskId} cannot be cancelled.`);task.status=ScheduledTaskStatus.CANCELLED;this.refresh();return clone(task)}
 private transitionRunning(taskId:string,status:"COMPLETED"|"FAILED"){const task=this.tasks.get(taskId);if(!task||task.status!==ScheduledTaskStatus.RUNNING)throw new SchedulerPlanError("INVALID_TASK_TRANSITION",`Task ${taskId} is not running.`);task.status=status;this.refresh();return clone(task)}
 result():SchedulerResult{return {tasks:this.getTasks(),readyTaskIds:this.getReadyTasks().map(task=>task.taskId)}}
}
