import { mkdir, open, readFile, readdir, rename, rm } from "node:fs/promises";
import { join } from "node:path";
import { createHash, randomUUID } from "node:crypto";
import { validateWorkflowPlan, type WorkflowPlan } from "@local-orchestrator/contracts";
import { AgentType } from "../runtime/AgentType.js";
import { ExecutionStatus, JobStatus, isTerminalJobState, type JobProjectBinding } from "../job-types.js";
import type { JobStore } from "../job-store.js";
import type { WorktreeService } from "../worktree-service.js";
import type { ExecutionService } from "../execution-service.js";
import type { OrchestrationRuntime } from "../orchestration/OrchestrationRuntime.js";
import { MultiAgentScheduler } from "../scheduler/MultiAgentScheduler.js";
import { ScheduledTaskStatus, type ScheduledTask } from "../scheduler/SchedulerTypes.js";
import { retryTransientFilesystem } from "../transient-retry.js";

export const WorkflowStatus={ACCEPTED:"ACCEPTED",PREPARING:"PREPARING",READY:"READY",RUNNING:"RUNNING",COMPLETED:"COMPLETED",FAILED:"FAILED",CANCELLED:"CANCELLED",INTERRUPTED:"INTERRUPTED"} as const;
export type WorkflowStatus=typeof WorkflowStatus[keyof typeof WorkflowStatus];
export interface WorkflowProject { projectId:string; displayName:string; defaultBranch:string; commands:JobProjectBinding["commands"]; verification:NonNullable<JobProjectBinding["verification"]>; }
export interface WorkflowState { workflowStateVersion:1; workflowId:string; workflowVersion:1; projectId:string; status:WorkflowStatus; tasks:ScheduledTask[]; createdAt:string; updatedAt:string; currentTaskId?:string; submissionKeyDigest?:string; planDigest?:string; interruptedFrom?:WorkflowStatus; }
export class WorkflowError extends Error { constructor(public readonly code:"WORKFLOW_INVALID"|"WORKFLOW_NOT_FOUND"|"WORKFLOW_COMMAND_MISSING"|"WORKFLOW_COMMAND_UNAPPROVED"|"WORKFLOW_ALREADY_EXISTS",message:string){super(message);this.name=code;} }
class Store { constructor(private root:string){} path(id:string){if(!/^[A-Za-z0-9_-]+$/.test(id))throw new WorkflowError("WORKFLOW_INVALID","Unsafe workflow ID");return join(this.root,"workflows",id,"workflow-state.json")} async save(s:WorkflowState){const p=this.path(s.workflowId),t=`${p}.${randomUUID()}.tmp`;await mkdir(join(this.root,"workflows",s.workflowId),{recursive:true});try{const h=await open(t,"w");try{await h.writeFile(`${JSON.stringify(s)}\n`);await h.sync()}finally{await h.close()}await retryTransientFilesystem(()=>rename(t,p))}catch(e){await retryTransientFilesystem(()=>rm(t,{force:true})).catch(()=>undefined);throw e}}async load(id:string){try{const s=JSON.parse(await readFile(this.path(id),"utf8")) as WorkflowState;if(s.workflowStateVersion!==1||s.workflowId!==id||!Object.values(WorkflowStatus).includes(s.status))return undefined;return s}catch{return undefined}}async all(){try{return (await Promise.all((await readdir(join(this.root,"workflows"))).map(id=>this.load(id)))).filter((s):s is WorkflowState=>!!s)}catch{return []}} }
export class WorkflowRuntime { private store:Store;private schedulers=new Map<string,MultiAgentScheduler>();private active=new Map<string,Promise<void>>();private submissionClaims=new Map<string,Promise<void>>();constructor(private root:string,private jobs:JobStore,private worktrees:WorktreeService,private execution:ExecutionService,private orchestration:OrchestrationRuntime){this.store=new Store(root)}
 private async withSubmissionClaim<T>(id:string,action:()=>Promise<T>):Promise<T>{const prior=this.submissionClaims.get(id)??Promise.resolve();let release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve}),tail=prior.then(()=>gate);this.submissionClaims.set(id,tail);await prior;try{return await action()}finally{release();if(this.submissionClaims.get(id)===tail)this.submissionClaims.delete(id)}}
 private startPreparation(id:string,plan:WorkflowPlan,project:WorkflowProject,scheduler:MultiAgentScheduler){const operation=this.prepareAndRun(id,plan,project,scheduler).catch(async error=>{try{const current=await this.store.load(id);if(current&&current.status!==WorkflowStatus.CANCELLED){current.status=WorkflowStatus.FAILED;current.currentTaskId=undefined;current.updatedAt=new Date().toISOString();current.tasks=scheduler.getResult().tasks;await this.store.save(current)}}catch(persistError){console.error("Workflow background failure could not be persisted",String(persistError).slice(0,256))}console.error("Workflow background preparation failed",String(error).slice(0,256))});this.active.set(id,operation);void operation.then(()=>{if(this.active.get(id)===operation)this.active.delete(id)},()=>{if(this.active.get(id)===operation)this.active.delete(id)});return operation}
async submit(input:unknown,project:WorkflowProject,options:{idempotencyKey?:string}={}){
 const parsed=validateWorkflowPlan(input);if(!parsed.success)throw new WorkflowError("WORKFLOW_INVALID",JSON.stringify(parsed.errors));const plan=parsed.data;if(plan.projectId!==project.projectId)throw new WorkflowError("WORKFLOW_INVALID","Project mismatch");
 for(const task of plan.tasks){const compatible=project.commands.filter(command=>command.agentTypes?.includes(task.agentType as AgentType));if(compatible.length!==1)throw new WorkflowError("WORKFLOW_COMMAND_MISSING",`Task ${task.taskId} requires exactly one approved ${task.agentType} execution command.`);for(const commandId of task.verification?.requiredCommandIds??[]){const command=project.commands.find(item=>item.id===commandId);if(!command)throw new WorkflowError("WORKFLOW_COMMAND_UNAPPROVED",`Unapproved command ID: ${commandId}`);if(!command.verificationCheck)throw new WorkflowError("WORKFLOW_COMMAND_UNAPPROVED",`Command ${commandId} is not an approved verification command.`);}}
 const key=options.idempotencyKey?.trim();if(key!==undefined&&!/^[A-Za-z0-9._:-]{1,200}$/.test(key))throw new WorkflowError("WORKFLOW_INVALID","Invalid workflow idempotency key");const hash=(value:string)=>createHash("sha256").update(value).digest("hex"),submissionKeyDigest=key?hash(key):undefined,canonicalPlan={...plan,workflowId:undefined},planDigest=hash(JSON.stringify(canonicalPlan)),keyId=submissionKeyDigest?`${submissionKeyDigest.slice(0,8)}-${submissionKeyDigest.slice(8,12)}-${submissionKeyDigest.slice(12,16)}-${submissionKeyDigest.slice(16,20)}-${submissionKeyDigest.slice(20,32)}`:undefined,id=keyId?`WF-${keyId}`:(plan.workflowId??`WF-${randomUUID()}`);
 return this.withSubmissionClaim(id,async()=>{const existing=await this.store.load(id);if(existing){if(!(submissionKeyDigest&&existing.submissionKeyDigest===submissionKeyDigest&&existing.planDigest===planDigest))throw new WorkflowError("WORKFLOW_ALREADY_EXISTS","Workflow already exists");const recoverable=existing.status===WorkflowStatus.INTERRUPTED&&([WorkflowStatus.ACCEPTED,WorkflowStatus.PREPARING,WorkflowStatus.READY] as WorkflowStatus[]).includes(existing.interruptedFrom as WorkflowStatus);if(recoverable&&!this.active.has(id)){const definitions=plan.tasks.map(task=>({taskId:task.taskId,jobId:`${id}-${task.taskId}`,agentType:task.agentType==="CODEX"?AgentType.CODEX:AgentType.ANTIGRAVITY,dependencies:[...task.dependsOn]})),scheduler=new MultiAgentScheduler(definitions);this.schedulers.set(id,scheduler);existing.status=WorkflowStatus.ACCEPTED;existing.interruptedFrom=undefined;existing.updatedAt=new Date().toISOString();existing.tasks=scheduler.getResult().tasks;await this.store.save(existing);this.startPreparation(id,plan,project,scheduler)}return existing}
 const definitions=plan.tasks.map(task=>({taskId:task.taskId,jobId:`${id}-${task.taskId}`,agentType:task.agentType==="CODEX"?AgentType.CODEX:AgentType.ANTIGRAVITY,dependencies:[...task.dependsOn]})),scheduler=new MultiAgentScheduler(definitions);this.schedulers.set(id,scheduler);const now=new Date().toISOString(),state:WorkflowState={workflowStateVersion:1,workflowId:id,workflowVersion:1,projectId:plan.projectId,status:WorkflowStatus.ACCEPTED,tasks:scheduler.getResult().tasks,createdAt:now,updatedAt:now,...(submissionKeyDigest?{submissionKeyDigest,planDigest}:{})};await this.store.save(state);this.startPreparation(id,plan,project,scheduler);return state})}
 private async prepareAndRun(id:string,plan:WorkflowPlan,project:WorkflowProject,scheduler:MultiAgentScheduler){const state=await this.get(id);state.status=WorkflowStatus.PREPARING;state.interruptedFrom=undefined;state.updatedAt=new Date().toISOString();await this.store.save(state);await mkdir(join(this.root,"jobs"),{recursive:true});const now=state.createdAt,binding:JobProjectBinding={schemaVersion:1,projectId:project.projectId,displayName:project.displayName,repositoryPath:project.verification.canonicalPath,defaultBranch:project.defaultBranch,commands:project.commands,projectCreatedAt:now,projectUpdatedAt:now,boundAt:now,verification:project.verification};const ownerId=`${id}-owner`;let owner;if(await this.jobs.jobExists(ownerId))owner=await this.jobs.loadJob(ownerId);else owner=await this.jobs.createJob({jobId:ownerId,planId:id,projectId:plan.projectId,projectBinding:binding,agentType:AgentType.CODEX,metadata:{workflowId:id,workflowOwner:true}});const shared=await this.worktrees.ensureWorktree(owner);await this.jobs.setWorktreeMetadata(ownerId,{worktreePath:shared.path,branchName:shared.branchName,worktreeCreatedAt:shared.createdAt});for(const task of plan.tasks){const jobId=`${id}-${task.taskId}`,agentType=task.agentType==="CODEX"?AgentType.CODEX:AgentType.ANTIGRAVITY,selected=project.commands.find(command=>command.agentTypes?.includes(agentType))!,taskBinding={...binding,commands:[selected,...project.commands.filter(command=>command.id!==selected.id)]};if(!await this.jobs.jobExists(jobId))await this.jobs.createJob({jobId,planId:id,projectId:plan.projectId,projectBinding:taskBinding,agentType,metadata:{workflowId:id,workflowGoal:plan.goal,workflowTaskId:task.taskId,workflowInstruction:task.instruction,workflowRequiredCommandIds:[...(task.verification?.requiredCommandIds??[])],workflowExpectedArtifacts:[...(task.verification?.expectedArtifacts??[])]}});let job=await this.jobs.loadJob(jobId);if(job.state===JobStatus.DRAFT)job=await this.jobs.transitionJob(jobId,JobStatus.AWAITING_APPROVAL,"Workflow submitted for user approval");if(job.state===JobStatus.AWAITING_APPROVAL)job=await this.jobs.transitionJob(jobId,JobStatus.QUEUED,"Run Workflow explicitly approved this task");if(job.state!==JobStatus.QUEUED)throw new WorkflowError("WORKFLOW_ALREADY_EXISTS",`Task ${task.taskId} already owns execution state ${job.state}.`);await this.jobs.setWorktreeMetadata(jobId,{worktreePath:shared.path,branchName:shared.branchName,worktreeCreatedAt:shared.createdAt})}const current=await this.get(id);if(current.status===WorkflowStatus.CANCELLED)return;current.status=WorkflowStatus.READY;current.tasks=scheduler.getResult().tasks;current.updatedAt=new Date().toISOString();await this.store.save(current);await this.run(id)}
 async get(id:string){const state=await this.store.load(id);if(!state)throw new WorkflowError("WORKFLOW_NOT_FOUND","Workflow was not found");return state} async cancel(id:string){const state=await this.get(id),scheduler=this.schedulers.get(id);if(state.status===WorkflowStatus.CANCELLED)return state;if(!scheduler){if(!([WorkflowStatus.COMPLETED,WorkflowStatus.FAILED,WorkflowStatus.CANCELLED,WorkflowStatus.INTERRUPTED] as WorkflowStatus[]).includes(state.status)){state.status=WorkflowStatus.CANCELLED;state.updatedAt=new Date().toISOString();await this.store.save(state)}return state}for(const task of scheduler.getResult().tasks){if(task.status===ScheduledTaskStatus.RUNNING)await this.execution.cancel(await this.jobs.loadJob(task.jobId));else if(task.status===ScheduledTaskStatus.PENDING||task.status===ScheduledTaskStatus.READY)scheduler.cancel(task.taskId)}state.status=WorkflowStatus.CANCELLED;state.tasks=scheduler.getResult().tasks;state.currentTaskId=undefined;state.updatedAt=new Date().toISOString();await this.store.save(state);return state}
 async reconcile(){for(const state of await this.store.all())if(([WorkflowStatus.ACCEPTED,WorkflowStatus.PREPARING,WorkflowStatus.READY,WorkflowStatus.RUNNING] as WorkflowStatus[]).includes(state.status)){state.interruptedFrom=state.status;state.status=WorkflowStatus.INTERRUPTED;state.currentTaskId=undefined;state.updatedAt=new Date().toISOString();await this.store.save(state)}} async waitForIdle(){await new Promise<void>(resolve=>setImmediate(resolve));await Promise.all([...this.active.values()])}
 private async run(id:string){const scheduler=this.schedulers.get(id);if(!scheduler)return;const state=await this.get(id);state.status=WorkflowStatus.RUNNING;state.updatedAt=new Date().toISOString();await this.store.save(state);while(state.status===WorkflowStatus.RUNNING){const task=scheduler.getReadyTasks()[0];if(!task)break;state.currentTaskId=task.taskId;scheduler.start(task.taskId);state.tasks=scheduler.getResult().tasks;state.updatedAt=new Date().toISOString();await this.store.save(state);try{await this.jobs.transitionJob(task.jobId,JobStatus.PREPARING,"Workflow task preparation started");await this.jobs.transitionJob(task.jobId,JobStatus.RUNNING_AGENTS,"Workflow scheduler started the approved task");const job=await this.jobs.loadJob(task.jobId),started=await this.execution.start(job);await started.completion;const final=await this.jobs.loadJob(task.jobId),pkg=await this.orchestration.processTerminal(task.jobId,{task:scheduler.plan.getTask(task.taskId),executionId:started.executionId});if(final.executionStatus===ExecutionStatus.CANCELLED){scheduler.cancel(task.taskId);await this.transitionIfActive(task.jobId,JobStatus.CANCELLED,"Workflow task execution was cancelled");}else if(final.executionStatus===ExecutionStatus.COMPLETED&&pkg?.status==="PASS"){scheduler.complete(task.taskId);for(const next of [JobStatus.INTEGRATING,JobStatus.TESTING,JobStatus.BUILDING_REVIEW_PACKAGE,JobStatus.AWAITING_REVIEW,JobStatus.COMPLETED])await this.jobs.transitionJob(task.jobId,next,"Workflow task completed reviewed execution");}else{scheduler.fail(task.taskId);await this.transitionIfActive(task.jobId,JobStatus.FAILED,"Workflow task execution or review failed");}}catch{if(scheduler.plan.getTask(task.taskId).status===ScheduledTaskStatus.RUNNING)scheduler.fail(task.taskId);await this.transitionIfActive(task.jobId,JobStatus.FAILED,"Workflow task failed before terminal review").catch(()=>undefined)}state.currentTaskId=undefined;state.tasks=scheduler.getResult().tasks;state.updatedAt=new Date().toISOString();await this.store.save(state)}const tasks=scheduler.getResult().tasks;state.tasks=tasks;state.status=(state.status as WorkflowStatus)===WorkflowStatus.CANCELLED||tasks.some(x=>x.status===ScheduledTaskStatus.CANCELLED)?WorkflowStatus.CANCELLED:tasks.every(x=>x.status===ScheduledTaskStatus.COMPLETED)?WorkflowStatus.COMPLETED:WorkflowStatus.FAILED;state.updatedAt=new Date().toISOString();await this.store.save(state)}
 private async transitionIfActive(jobId:string,to:typeof JobStatus.FAILED|typeof JobStatus.CANCELLED,reason:string){const job=await this.jobs.loadJob(jobId);if(!isTerminalJobState(job.state))await this.jobs.transitionJob(jobId,to,reason)} }
