import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtemp, rm, readFile, writeFile, access } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { JobStore, JobStatus, JobStoreError, JobStoreErrorCode, canTransitionJob, getAllowedTransitions, isTerminalJobState } from "../src/index.js";
import { JobLock } from "../src/job-lock.js";
let root:string; let store:JobStore;
beforeEach(async()=>{root=await mkdtemp(join(tmpdir(),"orchestrator-"));store=new JobStore(root)}); afterEach(async()=>{await rm(root,{recursive:true,force:true})});
const create=()=>store.createJob({jobId:"JOB-1",planId:"PLAN-1",projectId:"P-1"});
const err=(p:Promise<unknown>,code:string)=>expect(p).rejects.toMatchObject({code});
describe("state machine",()=>{
it("allows approval",()=>expect(canTransitionJob(JobStatus.DRAFT,JobStatus.AWAITING_APPROVAL)).toBe(true));
it("rejects invalid transition",()=>expect(canTransitionJob(JobStatus.DRAFT,JobStatus.COMPLETED)).toBe(false));
it("rejects terminal transition",()=>expect(canTransitionJob(JobStatus.FAILED,JobStatus.RUNNING_AGENTS)).toBe(false));
it("rejects same state",()=>expect(canTransitionJob(JobStatus.QUEUED,JobStatus.QUEUED)).toBe(false));
it("returns independent transition list",()=>{const x=getAllowedTransitions(JobStatus.QUEUED);x.push(JobStatus.COMPLETED);expect(getAllowedTransitions(JobStatus.QUEUED)).not.toContain(JobStatus.COMPLETED)});
it("identifies terminal states",()=>{expect(isTerminalJobState(JobStatus.COMPLETED)).toBe(true);expect(isTerminalJobState(JobStatus.PAUSED)).toBe(false)});
it("supports paused recovery",()=>expect(canTransitionJob(JobStatus.PAUSED,JobStatus.RUNNING_AGENTS)).toBe(true));
});
describe("store",()=>{
it("creates draft",async()=>expect((await create()).state).toBe(JobStatus.DRAFT));
it("writes created event",async()=>{await create();expect((await store.listEvents("JOB-1"))[0].type).toBe("JOB_CREATED")});
it("starts sequence at one",async()=>expect((await create()).lastEventSequence).toBe(1));
it("rejects duplicate",async()=>{await create();await err(create(),JobStoreErrorCode.JOB_ALREADY_EXISTS)});
it("loads after reopening",async()=>{await create();expect((await new JobStore(root).loadJob("JOB-1")).jobId).toBe("JOB-1")});
it("reports existence",async()=>{expect(await store.jobExists("JOB-1")).toBe(false);await create();expect(await store.jobExists("JOB-1")).toBe(true)});
it("persists transition",async()=>{await create();await store.transitionJob("JOB-1",JobStatus.AWAITING_APPROVAL,"submit");expect((await store.loadJob("JOB-1")).state).toBe(JobStatus.AWAITING_APPROVAL)});
it("updates timestamp",async()=>{const a=await create();const b=await store.transitionJob("JOB-1",JobStatus.AWAITING_APPROVAL,"submit");expect(b.updatedAt).not.toBe(a.updatedAt)});
it("increments event sequence",async()=>{await create();await store.transitionJob("JOB-1",JobStatus.AWAITING_APPROVAL,"one");expect((await store.transitionJob("JOB-1",JobStatus.QUEUED,"two")).lastEventSequence).toBe(3)});
it("lists ordered events",async()=>{await create();await store.transitionJob("JOB-1",JobStatus.AWAITING_APPROVAL,"one");expect((await store.listEvents("JOB-1")).map(x=>x.sequence)).toEqual([1,2])});
it("requires reason",async()=>{await create();await err(store.transitionJob("JOB-1",JobStatus.AWAITING_APPROVAL," "),JobStoreErrorCode.INVALID_TRANSITION)});
it("rejects invalid store transition",async()=>{await create();await err(store.transitionJob("JOB-1",JobStatus.COMPLETED,"bad"),JobStoreErrorCode.INVALID_TRANSITION)});
it("cancels queued job",async()=>{await create();await store.transitionJob("JOB-1",JobStatus.AWAITING_APPROVAL,"a");await store.transitionJob("JOB-1",JobStatus.QUEUED,"q");expect((await store.cancelJob("JOB-1","stop")).state).toBe(JobStatus.CANCELLED)});
it("rejects terminal cancellation",async()=>{await create();await store.transitionJob("JOB-1",JobStatus.AWAITING_APPROVAL,"a");await store.cancelJob("JOB-1","stop");await err(store.cancelJob("JOB-1","again"),JobStoreErrorCode.INVALID_TRANSITION)});
it("fix round increments in review",async()=>{await create();for(const s of [JobStatus.AWAITING_APPROVAL,JobStatus.QUEUED,JobStatus.PREPARING,JobStatus.RUNNING_AGENTS,JobStatus.INTEGRATING,JobStatus.TESTING,JobStatus.BUILDING_REVIEW_PACKAGE,JobStatus.AWAITING_REVIEW])await store.transitionJob("JOB-1",s,"go");expect((await store.incrementFixRound("JOB-1","fix")).fixRound).toBe(1)});
it("enforces fix limit",async()=>{await create();for(const s of [JobStatus.AWAITING_APPROVAL,JobStatus.QUEUED,JobStatus.PREPARING,JobStatus.RUNNING_AGENTS,JobStatus.INTEGRATING,JobStatus.TESTING,JobStatus.BUILDING_REVIEW_PACKAGE,JobStatus.AWAITING_REVIEW])await store.transitionJob("JOB-1",s,"go");await store.incrementFixRound("JOB-1","fix");await store.incrementFixRound("JOB-1","again");await err(store.incrementFixRound("JOB-1","third"),JobStoreErrorCode.FIX_ROUND_LIMIT_EXCEEDED)});
it("rejects fix in draft",async()=>{await create();await err(store.incrementFixRound("JOB-1","x"),JobStoreErrorCode.INVALID_TRANSITION)});
it("uses atomic state file",async()=>{await create();expect(JSON.parse(await readFile(join(root,"JOB-1","job-state.json"))).schemaVersion).toBe("1.0")});
it("lock is exclusive",async()=>{const p=join(root,"x.lock");const a=await JobLock.acquire(p);await err(JobLock.acquire(p),JobStoreErrorCode.JOB_LOCKED);await a.release()});
it("lock releases",async()=>{const p=join(root,"x.lock");const a=await JobLock.acquire(p);await a.release();const b=await JobLock.acquire(p);await b.release();expect(true).toBe(true)});
it("transition releases lock on error",async()=>{await create();await err(store.transitionJob("JOB-1",JobStatus.COMPLETED,"x"),JobStoreErrorCode.INVALID_TRANSITION);await access(join(root,"JOB-1",".job.lock")).catch(()=>undefined);expect(await store.jobExists("JOB-1")).toBe(true)});
it("detects corrupt state",async()=>{await create();await writeFile(join(root,"JOB-1","job-state.json"),"{");await err(store.loadJob("JOB-1"),JobStoreErrorCode.JOB_STATE_CORRUPTED)});
it("detects missing state",async()=>{await create();await rm(join(root,"JOB-1","job-state.json"));await err(store.loadJob("JOB-1"),JobStoreErrorCode.JOB_NOT_FOUND)});
it("detects missing fields",async()=>{await create();await writeFile(join(root,"JOB-1","job-state.json"),JSON.stringify({}));await err(store.loadJob("JOB-1"),JobStoreErrorCode.INVALID_JOB_RECORD)});
it("detects corrupt event JSON",async()=>{await create();await writeFile(join(root,"JOB-1","events.jsonl"),"bad\n");await err(store.listEvents("JOB-1"),JobStoreErrorCode.JOB_EVENT_LOG_CORRUPTED)});
it("detects skipped event sequence",async()=>{await create();const p=join(root,"JOB-1","events.jsonl");const lines=(await readFile(p,"utf8")).replace('"sequence":1','"sequence":2');await writeFile(p,lines);await err(store.listEvents("JOB-1"),JobStoreErrorCode.JOB_EVENT_LOG_CORRUPTED)});
it("detects event job mismatch",async()=>{await create();const p=join(root,"JOB-1","events.jsonl");const lines=(await readFile(p,"utf8")).replace('JOB-1','OTHER');await writeFile(p,lines);await err(store.listEvents("JOB-1"),JobStoreErrorCode.JOB_EVENT_LOG_CORRUPTED)});
it("detects state/log sequence mismatch",async()=>{await create();const p=join(root,"JOB-1","job-state.json");const x=JSON.parse(await readFile(p,"utf8"));x.lastEventSequence=4;await writeFile(p,JSON.stringify(x));await err(store.listEvents("JOB-1"),JobStoreErrorCode.JOB_EVENT_LOG_CORRUPTED)});
});