import {describe,expect,it} from "vitest";
import {ExecutionStatus} from "../src/job-types.js";
import {AgentType} from "../src/runtime/AgentType.js";
import {ReviewRuntime} from "../src/review/ReviewRuntime.js";
import {ReviewStatus,VerificationStatus,type ReviewEvidence,type ReviewRule} from "../src/review/ReviewTypes.js";

const evidence=(overrides:Partial<ReviewEvidence>={}):ReviewEvidence=>({jobId:"JOB-012",taskId:"task-012",agentType:AgentType.CODEX,executionStatus:ExecutionStatus.COMPLETED,exitCode:0,changedFiles:["src/main.ts"],verification:{build:VerificationStatus.PASS,typecheck:VerificationStatus.PASS,tests:VerificationStatus.PASS},...overrides});
const runtime=new ReviewRuntime();

describe("ReviewRuntime",()=>{
 it("accepts valid CODEX and ANTIGRAVITY evidence and returns PASS",()=>{expect(runtime.review(evidence()).status).toBe(ReviewStatus.PASS);expect(runtime.review(evidence({agentType:AgentType.ANTIGRAVITY})).status).toBe(ReviewStatus.PASS);});
 it("requires every verification check by default",()=>{for(const verification of [{build:VerificationStatus.UNKNOWN,typecheck:VerificationStatus.PASS,tests:VerificationStatus.PASS},{build:VerificationStatus.PASS,typecheck:VerificationStatus.NOT_RUN,tests:VerificationStatus.PASS},{build:VerificationStatus.PASS,typecheck:VerificationStatus.PASS,tests:VerificationStatus.UNKNOWN}]){expect(runtime.review(evidence({verification})).status).not.toBe(ReviewStatus.PASS);}const missing=runtime.review(evidence({verification:undefined}));expect(missing.status).toBe(ReviewStatus.NEEDS_REPAIR);expect(missing.issues.map(issue=>issue.code)).toEqual(["BUILD_MISSING","TESTS_MISSING","TYPECHECK_MISSING"]);});
 it("allows missing optional verification only when explicitly declared",()=>{const result=runtime.review(evidence({verification:{build:VerificationStatus.PASS,tests:VerificationStatus.PASS},constraints:{optionalVerification:["typecheck"]}}));expect(result.status).toBe(ReviewStatus.PASS);expect(result.issues).toEqual([]);});
 it("rejects invalid evidence with deterministic non-repairable issues",()=>{const result=runtime.review(evidence({jobId:"",changedFiles:["src/a.ts","src/a.ts"]}));expect(result.status).toBe(ReviewStatus.FAIL);expect(result.issues.map(issue=>issue.code)).toEqual(["INVALID_CHANGED_FILES","INVALID_JOB_ID"]);expect(result.issues.every(issue=>!issue.repairable)).toBe(true);});
 it("is deterministic for identical evidence and sorts configured rules and issues",()=>{const first=runtime.review(evidence({executionStatus:ExecutionStatus.FAILED,exitCode:2,verification:{tests:VerificationStatus.FAIL,build:VerificationStatus.FAIL}})),second=runtime.review(evidence({executionStatus:ExecutionStatus.FAILED,exitCode:2,verification:{tests:VerificationStatus.FAIL,build:VerificationStatus.FAIL}}));expect(second).toEqual(first);expect(first.issues.map(issue=>`${issue.ruleId}:${issue.code}`)).toEqual(["execution-outcome:EXECUTION_FAILED","exit-code:NONZERO_EXIT_CODE","verification:BUILD_FAILED","verification:TESTS_FAILED","verification:TYPECHECK_MISSING"]);});
 it("classifies failed execution, nonzero exit, and verification failures as repairable",()=>{const result=runtime.review(evidence({executionStatus:ExecutionStatus.FAILED,exitCode:4,verification:{build:VerificationStatus.FAIL,typecheck:VerificationStatus.FAIL,tests:VerificationStatus.FAIL}}));expect(result.status).toBe(ReviewStatus.NEEDS_REPAIR);expect(result.issues).toHaveLength(5);expect(result.issues.every(issue=>issue.repairable)).toBe(true);});
 it("does not allow cancelled or incomplete execution to pass",()=>{expect(runtime.review(evidence({executionStatus:ExecutionStatus.CANCELLED})).status).toBe(ReviewStatus.NEEDS_REPAIR);expect(runtime.review(evidence({executionStatus:ExecutionStatus.RUNNING})).status).toBe(ReviewStatus.FAIL);});
 it("does not create an exit-code issue for zero or unavailable exit codes",()=>{expect(runtime.review(evidence({exitCode:0})).issues.some(issue=>issue.code==="NONZERO_EXIT_CODE")).toBe(false);expect(runtime.review(evidence({exitCode:undefined})).issues.some(issue=>issue.code==="NONZERO_EXIT_CODE")).toBe(false);});
 it("enforces generic allowed and forbidden path constraints",()=>{const allowed=runtime.review(evidence({changedFiles:["src/main.ts"],constraints:{allowedPaths:["src"]}}));expect(allowed.issues).toEqual([]);const outside=runtime.review(evidence({changedFiles:["docs/a.md"],constraints:{allowedPaths:["src"]}}));expect(outside.status).toBe(ReviewStatus.FAIL);expect(outside.issues[0]).toMatchObject({code:"OUTSIDE_ALLOWED_SCOPE",path:"docs/a.md",repairable:false});const forbidden=runtime.review(evidence({changedFiles:["src/private/a.ts"],constraints:{forbiddenPaths:["src/private"]}}));expect(forbidden.issues[0]).toMatchObject({code:"FORBIDDEN_PATH_CHANGED",path:"src/private/a.ts",repairable:false});});
 it("checks required artifacts deterministically",()=>{const present=runtime.review(evidence({constraints:{requiredArtifacts:["reports/result.md"],observedArtifacts:["reports/result.md"]}}));expect(present.status).toBe(ReviewStatus.PASS);const missing=runtime.review(evidence({constraints:{requiredArtifacts:["z.md","a.md"],observedArtifacts:[]}}));expect(missing.status).toBe(ReviewStatus.NEEDS_REPAIR);expect(missing.issues.map(issue=>issue.path)).toEqual(["a.md","z.md"]);});
 it("fails non-repairable custom policy issues",()=>{const policy:ReviewRule={id:"policy",evaluate:()=>[{code:"POLICY",severity:"ERROR",message:"Policy violation.",ruleId:"policy",repairable:false}]};expect(new ReviewRuntime([policy]).review(evidence()).status).toBe(ReviewStatus.FAIL);});
 it("keeps the review boundary free of execution, prompt, streaming, and scheduler mutation",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile(new URL("../src/review/ReviewRuntime.ts",import.meta.url),"utf8"));expect(source).not.toMatch(/ProcessRunner|AgentFactory|PromptBuilder|StreamingRuntime|ExecutionService|SchedulerPlan/);});
});
