import { BridgeClient } from "./bridge/bridge-client.js";
import { createResultReturnRecord, RESULT_DELIVERY_COMMAND_TYPE, type ResultReturnRecord, type WorkflowSourceBinding } from "./result-return.js";
import { encodeWorkflowResultHandoff } from "./workflow-result-handoff.js";
import { BROWSER_SUPERVISOR_DIAGNOSTIC_LIMIT, type BrowserSupervisorDiagnosticObservation, type BrowserSupervisorDiagnosticSnapshot, type BrowserSupervisorContentStatus, type BrowserSupervisorSourceStatus } from "@local-orchestrator/contracts";

export const SUPERVISOR_ALARM = "local-orchestrator-browser-supervisor";
export const SUPERVISOR_TICK_MINUTES = 1;
export const BROWSER_LEASE_MS = 60_000;
export const CONTENT_PING = "LOCAL_ORCHESTRATOR_CONTENT_PING";
export const CONTENT_CAPTURE_PROBE = "LOCAL_ORCHESTRATOR_CONTENT_CAPTURE_PROBE";
export const RESULT_RECONCILE = "LOCAL_ORCHESTRATOR_RECONCILE_RESULT";
export const SUPERVISOR_HEALTH = "LOCAL_ORCHESTRATOR_SUPERVISOR_HEALTH";
export const BROWSER_JOB_PROGRESS = "LOCAL_ORCHESTRATOR_BROWSER_JOB_PROGRESS";
export const SUPERVISOR_DIAGNOSTIC_OUTAGE_CHANGED = "LOCAL_ORCHESTRATOR_SUPERVISOR_DIAGNOSTIC_OUTAGE_CHANGED";

export type SupervisionState="ACTIVE"|"WAITING_BRIDGE"|"RESULT_QUEUED"|"DELIVERED"|"FAILED_SAFE";
export interface WorkflowSupervisionRecord {supervisionVersion:1;workflowId:string;projectId:string;sourceConversationUrl:string;sourceOrigin:"https://chatgpt.com";sourceTabId:number;workflowHandoffDigest:string;state:SupervisionState;createdAt:string;updatedAt:string;lastBridgeCheckAt?:string;lastBrowserCheckAt?:string;lastObservedWorkflowStatus?:string;terminalResultDigest?:string;lastError?:string;}
export interface SupervisorRegistrationDiagnostic {registrationRequested:true;registrationPersisted:boolean;workflowId:string;supervisionState:SupervisionState|"NOT_REGISTERED";lastBridgeState:string;lastRegistrationError?:string;observedAt:string;}
export type BrowserJobState="QUEUED"|"LEASED"|"WAITING_SOURCE"|"AWAITING_RECONCILIATION"|"DELIVERED"|"FAILED_SAFE";
export interface BrowserJob {browserJobVersion:1;browserJobId:string;operationType:"RESULT_RETURN";workflowId:string;resultDigest:string;sourceConversationUrl:string;sourceOrigin:"https://chatgpt.com";sourceTabId:number;state:BrowserJobState;leaseId?:string;leaseExpiresAt?:string;attempts:number;deadlineAt:string;lastStage:string;lastStageDetail?:string;lastHeartbeatAt?:string;deliveryCommittedAt?:string;sendAttemptedAt?:string;awaitingReconciliationAt?:string;createdAt:string;updatedAt:string;deliveredAt?:string;}
export interface SupervisorHealth {enabled:boolean;lastSupervisorTick?:string;bridgeReachable:boolean;sourceTabConnected:boolean;contentScriptReady:boolean;activeSupervisedWorkflows:number;queuedBrowserJobs:number;leasedBrowserJobs:number;lastHeartbeat?:string;lastFailure?:string;}
export interface SupervisorStore {enabled():Promise<boolean>;autoReturnEnabled():Promise<boolean>;bridgeOutageEnabled?():Promise<boolean>;token():Promise<string|null>;binding(id:string):Promise<WorkflowSourceBinding|null>;supervisions():Promise<Record<string,WorkflowSupervisionRecord>>;saveSupervision(value:WorkflowSupervisionRecord):Promise<void>;register?(binding:WorkflowSourceBinding,value:WorkflowSupervisionRecord,diagnostic:SupervisorRegistrationDiagnostic):Promise<void>;saveRegistrationDiagnostic?(value:SupervisorRegistrationDiagnostic):Promise<void>;jobs():Promise<Record<string,BrowserJob>>;saveJob(value:BrowserJob):Promise<void>;result(id:string):Promise<ResultReturnRecord|null>;saveResult(value:ResultReturnRecord):Promise<void>;complete?(job:BrowserJob,result:ResultReturnRecord,supervision:WorkflowSupervisionRecord):Promise<void>;saveHealth(value:SupervisorHealth):Promise<void>;observations?():Promise<BrowserSupervisorDiagnosticObservation[]>;saveObservation?(value:BrowserSupervisorDiagnosticObservation):Promise<void>;}
export interface SupervisorTabs {get(id:number):Promise<{id?:number;url?:string}>;queryExact(url:string):Promise<Array<{id?:number;url?:string}>>;send(id:number,message:unknown):Promise<unknown>;inject(id:number):Promise<void>;}
export interface SupervisorBridge {getWorkflow(id:string,token:string):Promise<{workflowId:string;projectId:string;status:string}>;getWorkflowResultPackage(id:string,token:string):Promise<any>;publishBrowserSupervisorDiagnostics?(value:BrowserSupervisorDiagnosticSnapshot,token:string):Promise<unknown>;}
const terminal=new Set(["COMPLETED","FAILED","CANCELLED","INTERRUPTED"]);
const activeTicks=new Map<string,Promise<void>>();
const iso=(now:()=>Date)=>now().toISOString();
const bounded=(value:unknown)=>typeof value==="string"?value.slice(0,256):undefined;
const contentReady=(value:unknown)=>{const state=value as {status?:unknown;instanceVersion?:unknown;captureInitialized?:unknown;captureObserverActive?:unknown;runtimeMessagingReady?:unknown;observerTargetConnected?:unknown;resultDeliveryInitialized?:unknown};return state?.status==="READY"&&state.instanceVersion===2&&state.captureInitialized===true&&state.captureObserverActive===true&&state.runtimeMessagingReady===true&&state.observerTargetConnected===true&&state.resultDeliveryInitialized===true};
const deliveryCommitted=(job:BrowserJob)=>Boolean(job.deliveryCommittedAt||job.sendAttemptedAt||job.awaitingReconciliationAt||job.attempts>0);
function trustedConversationUrl(value:string):boolean{try{const url=new URL(value),parts=url.pathname.split("/").filter(Boolean),index=parts.indexOf("c");return url.origin==="https://chatgpt.com"&&index>=0&&typeof parts[index+1]==="string"&&parts[index+1]!.length>0}catch{return false}}

export class BrowserSupervisor {
  constructor(private readonly store:SupervisorStore,private readonly tabs:SupervisorTabs,private readonly bridge:SupervisorBridge=new BridgeClient(),private readonly now=()=>new Date(),private readonly uuid=()=>crypto.randomUUID()){}
  async supervise(workflowId:string,projectId:string,sourceBinding?:WorkflowSourceBinding):Promise<WorkflowSupervisionRecord|null>{if(!await this.store.enabled())return null;const binding=sourceBinding??await this.store.binding(workflowId);if(!binding||binding.workflowId!==workflowId||binding.sourceOrigin!=="https://chatgpt.com"||!trustedConversationUrl(binding.sourceConversationUrl))return null;const stamp=iso(this.now),value:WorkflowSupervisionRecord={supervisionVersion:1,workflowId,projectId,sourceConversationUrl:binding.sourceConversationUrl,sourceOrigin:binding.sourceOrigin,sourceTabId:binding.sourceTabId,workflowHandoffDigest:binding.workflowHandoffDigest,state:"ACTIVE",createdAt:stamp,updatedAt:stamp},diagnostic:SupervisorRegistrationDiagnostic={registrationRequested:true,registrationPersisted:true,workflowId,supervisionState:"ACTIVE",lastBridgeState:"NOT_POLLED",observedAt:stamp};if(sourceBinding&&this.store.register)await this.store.register(binding,value,diagnostic);else{await this.store.saveSupervision(value);await this.store.saveRegistrationDiagnostic?.(diagnostic)}void this.tick().catch(error=>console.warn("Browser Supervisor detached tick failed",bounded(error instanceof Error?error.message:error)));return value}
  async tick():Promise<void>{const running=activeTicks.get("tick");if(running)return running;const operation=this.runTick();activeTicks.set("tick",operation);try{await operation}finally{if(activeTicks.get("tick")===operation)activeTicks.delete("tick")}}
  private async runTick():Promise<void>{const enabled=await this.store.enabled(),stamp=iso(this.now);if(!enabled){await this.health({enabled,lastSupervisorTick:stamp});return}const records=await this.store.supervisions();for(const record of Object.values(records))if(record.state!=="DELIVERED"&&record.state!=="FAILED_SAFE")await this.discover(record);const jobs=await this.store.jobs();if(await this.store.autoReturnEnabled())for(const job of Object.values(jobs))if(job.state!=="DELIVERED"&&job.state!=="FAILED_SAFE")await this.processJob(job);await this.health({enabled,lastSupervisorTick:stamp})}
  private async registrationDiagnostic(record:WorkflowSupervisionRecord,lastBridgeState:string,lastRegistrationError?:string):Promise<void>{await this.store.saveRegistrationDiagnostic?.({registrationRequested:true,registrationPersisted:true,workflowId:record.workflowId,supervisionState:record.state,lastBridgeState,lastRegistrationError:bounded(lastRegistrationError),observedAt:iso(this.now)})}
  private async discover(record:WorkflowSupervisionRecord):Promise<void>{
    const token=await this.store.token(),stamp=iso(this.now);
    if(!token){const next={...record,state:"WAITING_BRIDGE" as const,lastBridgeCheckAt:stamp,updatedAt:stamp,lastError:"BRIDGE_TOKEN_UNAVAILABLE"};await this.store.saveSupervision(next);await this.registrationDiagnostic(next,"BRIDGE_TOKEN_UNAVAILABLE",next.lastError);return}
    if(await this.store.bridgeOutageEnabled?.()){const next={...record,state:"WAITING_BRIDGE" as const,lastBridgeCheckAt:stamp,updatedAt:stamp,lastError:"SIMULATED_BRIDGE_OUTAGE"};await this.store.saveSupervision(next);await this.registrationDiagnostic(next,"SIMULATED_BRIDGE_OUTAGE",next.lastError);return}
    try{
      const workflow=await this.bridge.getWorkflow(record.workflowId,token);
      if(!terminal.has(workflow.status)){const next={...record,state:"ACTIVE" as const,lastBridgeCheckAt:stamp,lastObservedWorkflowStatus:workflow.status,updatedAt:stamp,lastError:undefined};await this.store.saveSupervision(next);await this.registrationDiagnostic(next,workflow.status);return}
      const result=await this.bridge.getWorkflowResultPackage(record.workflowId,token),binding=await this.store.binding(record.workflowId);
      if(!binding){await this.registrationDiagnostic(record,workflow.status,"SOURCE_BINDING_MISSING");return}
      const resultRecord=await createResultReturnRecord(result,binding,this.now),existing=await this.store.result(record.workflowId);
      if(existing?.resultDigest===resultRecord.resultDigest&&existing.status==="DELIVERED"){const next={...record,state:"DELIVERED" as const,terminalResultDigest:resultRecord.resultDigest,lastBridgeCheckAt:stamp,lastObservedWorkflowStatus:workflow.status,updatedAt:stamp};await this.store.saveSupervision(next);await this.registrationDiagnostic(next,workflow.status);return}
      await this.store.saveResult(existing?.resultDigest===resultRecord.resultDigest?existing:resultRecord);
      const jobs=await this.store.jobs(),existingJob=Object.values(jobs).find(value=>value.workflowId===record.workflowId&&value.resultDigest===resultRecord.resultDigest);
      if(existingJob?.state==="DELIVERED"){await this.store.saveResult({...resultRecord,status:"DELIVERED",attempts:existing?.attempts??existingJob.attempts,updatedAt:stamp,deliveredAt:existingJob.deliveredAt??stamp});const next={...record,state:"DELIVERED" as const,terminalResultDigest:resultRecord.resultDigest,lastBridgeCheckAt:stamp,lastObservedWorkflowStatus:workflow.status,updatedAt:stamp};await this.store.saveSupervision(next);await this.registrationDiagnostic(next,workflow.status);return}
      if(!existingJob){const job:BrowserJob={browserJobVersion:1,browserJobId:`BJ-${record.workflowId}-${resultRecord.resultDigest.slice(0,16)}`,operationType:"RESULT_RETURN",workflowId:record.workflowId,resultDigest:resultRecord.resultDigest,sourceConversationUrl:record.sourceConversationUrl,sourceOrigin:record.sourceOrigin,sourceTabId:record.sourceTabId,state:"QUEUED",attempts:0,deadlineAt:new Date(this.now().getTime()+24*60*60_000).toISOString(),lastStage:"QUEUED",createdAt:stamp,updatedAt:stamp};await this.store.saveJob(job)}
      const next={...record,state:"RESULT_QUEUED" as const,terminalResultDigest:resultRecord.resultDigest,lastBridgeCheckAt:stamp,lastObservedWorkflowStatus:workflow.status,updatedAt:stamp,lastError:undefined};await this.store.saveSupervision(next);await this.registrationDiagnostic(next,workflow.status);
    }catch(error){const message=bounded(error instanceof Error?error.message:error),next={...record,state:"WAITING_BRIDGE" as const,lastBridgeCheckAt:stamp,updatedAt:stamp,lastError:message};await this.store.saveSupervision(next);await this.registrationDiagnostic(next,"BRIDGE_ERROR",message)}
  }
  private async resolveSource(job:BrowserJob):Promise<number|null>{try{const tab=await this.tabs.get(job.sourceTabId);if(tab.id===job.sourceTabId&&tab.url===job.sourceConversationUrl)return job.sourceTabId}catch{}const exact=(await this.tabs.queryExact(job.sourceConversationUrl)).filter(tab=>tab.id!==undefined&&tab.url===job.sourceConversationUrl);if(exact.length!==1)return null;const tabId=exact[0]!.id!;await this.store.saveJob({...job,sourceTabId:tabId,lastStage:"SOURCE_REBOUND",updatedAt:iso(this.now)});return tabId}
  private async ensureContent(tabId:number):Promise<boolean>{try{const value=await this.tabs.send(tabId,{type:CONTENT_PING});if(contentReady(value))return true}catch{}try{await this.tabs.inject(tabId);const value=await this.tabs.send(tabId,{type:CONTENT_PING});return contentReady(value)}catch{return false}}
  private async processJob(job:BrowserJob):Promise<void>{
    const nowMs=this.now().getTime();
    if(job.state==="LEASED"&&job.leaseExpiresAt&&Date.parse(job.leaseExpiresAt)>nowMs)return;
    const tabId=await this.resolveSource(job);
    if(tabId===null){const committed=deliveryCommitted(job);await this.store.saveJob({...job,state:committed?"AWAITING_RECONCILIATION":"WAITING_SOURCE",lastStage:committed?"AWAITING_RECONCILIATION":"WAITING_SOURCE",lastStageDetail:committed?"SOURCE_UNAVAILABLE_BROWSER_TRUTH_PENDING":job.lastStageDetail,updatedAt:iso(this.now)});return}
    if(!await this.ensureContent(tabId)){const committed=deliveryCommitted(job);await this.store.saveJob({...job,sourceTabId:tabId,state:committed?"AWAITING_RECONCILIATION":"WAITING_SOURCE",lastStage:committed?"AWAITING_RECONCILIATION":"CONTENT_SCRIPT_UNAVAILABLE",lastStageDetail:committed?"CONTENT_UNAVAILABLE_BROWSER_TRUTH_PENDING":job.lastStageDetail,updatedAt:iso(this.now)});return}
    const result=await this.store.result(job.workflowId);
    if(!result||result.resultDigest!==job.resultDigest){await this.store.saveJob({...job,state:"FAILED_SAFE",lastStage:"RESULT_UNAVAILABLE",updatedAt:iso(this.now)});return}
    if(result.status==="DELIVERED"){await this.complete(job,tabId,0);return}
    let reconciliation:unknown;
    try{reconciliation=await this.tabs.send(tabId,{type:RESULT_RECONCILE,workflowId:job.workflowId,resultDigest:job.resultDigest})}catch{const committed=deliveryCommitted(job);await this.store.saveJob({...job,sourceTabId:tabId,state:committed?"AWAITING_RECONCILIATION":"WAITING_SOURCE",lastStage:committed?"AWAITING_RECONCILIATION":"CONTENT_SCRIPT_UNAVAILABLE",lastStageDetail:committed?"RECONCILIATION_UNAVAILABLE_BROWSER_TRUTH_PENDING":job.lastStageDetail,updatedAt:iso(this.now)});return}
    if((reconciliation as any)?.delivered===true){await this.complete(job,tabId,0);return}
    if(deliveryCommitted(job)){const expired=Date.parse(job.deadlineAt)<=nowMs;await this.store.saveJob({...job,sourceTabId:tabId,state:expired?"FAILED_SAFE":"AWAITING_RECONCILIATION",leaseId:undefined,leaseExpiresAt:undefined,lastStage:expired?"DELIVERY_UNCONFIRMED":"AWAITING_RECONCILIATION",lastStageDetail:expired?"RECONCILIATION_DEADLINE_EXPIRED":"BROWSER_TRUTH_PENDING",updatedAt:iso(this.now)});return}
    const leaseId=this.uuid(),stamp=iso(this.now),leased:BrowserJob={...job,sourceTabId:tabId,state:"LEASED",leaseId,leaseExpiresAt:new Date(nowMs+BROWSER_LEASE_MS).toISOString(),lastStage:"RESULT_JOB_LEASED",updatedAt:stamp};
    await this.store.saveJob(leased);
    let response:unknown;
    try{response=await this.tabs.send(tabId,{type:RESULT_DELIVERY_COMMAND_TYPE,browserJobId:job.browserJobId,leaseId,payload:result.payload,workflowId:job.workflowId,resultDigest:job.resultDigest})}catch{const latest=(await this.store.jobs())[job.browserJobId];if(!latest||latest.leaseId!==leaseId)return;const committed=deliveryCommitted(latest);await this.store.saveJob({...latest,state:committed?"AWAITING_RECONCILIATION":"LEASED",leaseId:committed?undefined:latest.leaseId,leaseExpiresAt:committed?undefined:latest.leaseExpiresAt,awaitingReconciliationAt:committed?(latest.awaitingReconciliationAt??iso(this.now)):latest.awaitingReconciliationAt,lastStage:committed?"AWAITING_RECONCILIATION":"CONTENT_SCRIPT_UNAVAILABLE",lastStageDetail:committed?"DISPATCH_CONNECTION_LOST_BROWSER_TRUTH_PENDING":"DISPATCH_CONNECTION_LOST",updatedAt:iso(this.now)});return}
    const latest=(await this.store.jobs())[job.browserJobId];if(!latest||latest.leaseId!==leaseId)return;
    const value=response as {status?:unknown;reason?:unknown;attempts?:unknown};
    if(value.status==="DELIVERED"){await this.complete(latest,tabId,typeof value.attempts==="number"?value.attempts:0);return}
    const attempts=latest.attempts+(typeof value.attempts==="number"?value.attempts:0),committed=deliveryCommitted(latest);
    await this.store.saveJob({...latest,state:committed?"AWAITING_RECONCILIATION":"WAITING_SOURCE",attempts,leaseId:undefined,leaseExpiresAt:undefined,awaitingReconciliationAt:committed?(latest.awaitingReconciliationAt??iso(this.now)):undefined,lastStage:committed?"AWAITING_RECONCILIATION":"WAITING_SOURCE",lastStageDetail:bounded(value.reason),updatedAt:iso(this.now)})
  }
  async progress(message:{browserJobId?:unknown;leaseId?:unknown;stage?:unknown;detail?:unknown;heartbeat?:unknown},sourceTabId:number):Promise<boolean>{if(typeof message.browserJobId!=="string"||typeof message.leaseId!=="string")return false;const job=(await this.store.jobs())[message.browserJobId];if(!job||job.state!=="LEASED"||job.leaseId!==message.leaseId||job.sourceTabId!==sourceTabId)return false;const stamp=iso(this.now),heartbeat=message.heartbeat===true,stage=typeof message.stage==="string"?message.stage.slice(0,64):job.lastStage,committed=["COMPOSER_WRITE_RESERVED","COMPOSER_WRITTEN","SEND_ATTEMPTED","SEND_CLICKED","USER_TURN_NOT_OBSERVED"].includes(stage),sendAttempted=["SEND_ATTEMPTED","SEND_CLICKED","USER_TURN_NOT_OBSERVED"].includes(stage);await this.store.saveJob({...job,lastStage:stage,lastStageDetail:bounded(message.detail),lastHeartbeatAt:heartbeat?stamp:job.lastHeartbeatAt,leaseExpiresAt:heartbeat?new Date(this.now().getTime()+BROWSER_LEASE_MS).toISOString():job.leaseExpiresAt,deliveryCommittedAt:committed?(job.deliveryCommittedAt??stamp):job.deliveryCommittedAt,sendAttemptedAt:sendAttempted?(job.sendAttemptedAt??stamp):job.sendAttemptedAt,updatedAt:stamp});return true}
  private async complete(job:BrowserJob,tabId:number,attempts:number):Promise<void>{const stamp=iso(this.now),result=await this.store.result(job.workflowId),record=(await this.store.supervisions())[job.workflowId],deliveredJob={...job,sourceTabId:tabId,state:"DELIVERED" as const,attempts:job.attempts+attempts,leaseId:undefined,leaseExpiresAt:undefined,lastStage:"DELIVERED",updatedAt:stamp,deliveredAt:stamp};if(result&&record){const deliveredResult={...result,status:"DELIVERED" as const,attempts:result.attempts+attempts,updatedAt:stamp,deliveredAt:stamp,reason:undefined},deliveredSupervision={...record,state:"DELIVERED" as const,sourceTabId:tabId,updatedAt:stamp,lastBrowserCheckAt:stamp,lastError:undefined};if(this.store.complete)await this.store.complete(deliveredJob,deliveredResult,deliveredSupervision);else{await this.store.saveJob(deliveredJob);await this.store.saveResult(deliveredResult);await this.store.saveSupervision(deliveredSupervision)}await this.registrationDiagnostic(deliveredSupervision,record.lastObservedWorkflowStatus??"TERMINAL");return}await this.store.saveJob(deliveredJob);if(result)await this.store.saveResult({...result,status:"DELIVERED",attempts:result.attempts+attempts,updatedAt:stamp,deliveredAt:stamp,reason:undefined})}
  private sourceStatus(job?:BrowserJob):BrowserSupervisorSourceStatus{if(!job)return "UNKNOWN";if(job.lastStage==="SOURCE_REBOUND")return "REBOUND";return job.state==="WAITING_SOURCE"?"WAITING":"CONNECTED"}
  private contentStatus(job?:BrowserJob):BrowserSupervisorContentStatus{if(!job)return "UNKNOWN";if(job.lastStage==="CONTENT_SCRIPT_UNAVAILABLE")return "UNAVAILABLE";if(job.lastStage==="CONTENT_SCRIPT_CONNECTING")return "RECOVERING";return job.state==="WAITING_SOURCE"?"UNKNOWN":"READY"}
  private async health(seed:Partial<SupervisorHealth>):Promise<void>{
    const records=Object.values(await this.store.supervisions()),jobs=Object.values(await this.store.jobs()).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)),latest=jobs[0];
    const health:SupervisorHealth={enabled:seed.enabled??false,lastSupervisorTick:seed.lastSupervisorTick,bridgeReachable:!records.some(value=>value.state==="WAITING_BRIDGE"),sourceTabConnected:!jobs.some(value=>value.state==="WAITING_SOURCE"),contentScriptReady:!jobs.some(value=>value.lastStage==="CONTENT_SCRIPT_UNAVAILABLE"),activeSupervisedWorkflows:records.filter(value=>!["DELIVERED","FAILED_SAFE"].includes(value.state)).length,queuedBrowserJobs:jobs.filter(value=>["QUEUED","WAITING_SOURCE"].includes(value.state)).length,leasedBrowserJobs:jobs.filter(value=>value.state==="LEASED").length,lastHeartbeat:latest?.lastHeartbeatAt,lastFailure:latest?.lastStageDetail};
    await this.store.saveHealth(health);
    const observedAt=iso(this.now);
    if(this.store.saveObservation)for(const record of records){const matches=jobs.filter(job=>job.workflowId===record.workflowId),job=matches[0],result=await this.store.result(record.workflowId);await this.store.saveObservation({observedAt,workflowId:record.workflowId,supervisionState:record.state,workflowState:record.lastObservedWorkflowStatus,browserJobId:job?.browserJobId,browserJobState:job?.state,resultDeliveryState:result?.status,lastStage:job?.lastStage,lastStageDetail:bounded(job?.lastStageDetail)});}
    const observations=this.store.observations?(await this.store.observations()).slice(-BROWSER_SUPERVISOR_DIAGNOSTIC_LIMIT):[];
    const snapshot:BrowserSupervisorDiagnosticSnapshot={diagnosticVersion:1,observedAt,supervisorEnabled:health.enabled,lastSupervisorTick:health.lastSupervisorTick,bridgeStatus:health.bridgeReachable?"CONNECTED":"WAITING",sourceStatus:health.sourceTabConnected?"CONNECTED":"WAITING",contentScriptStatus:health.contentScriptReady?"READY":"UNAVAILABLE",activeSupervisedWorkflowCount:health.activeSupervisedWorkflows,queuedBrowserJobCount:health.queuedBrowserJobs,leasedBrowserJobCount:health.leasedBrowserJobs,lastHeartbeat:health.lastHeartbeat,lastFailure:bounded(health.lastFailure),workflows:await Promise.all(records.slice(-BROWSER_SUPERVISOR_DIAGNOSTIC_LIMIT).map(async record=>{const matches=jobs.filter(job=>job.workflowId===record.workflowId),job=matches[0],result=await this.store.result(record.workflowId),heartbeatAge=job?.lastHeartbeatAt?Math.max(0,this.now().getTime()-Date.parse(job.lastHeartbeatAt)):undefined;return{workflowId:record.workflowId,projectId:record.projectId,supervisionState:record.state,workflowState:record.lastObservedWorkflowStatus,browserJobId:job?.browserJobId,browserJobState:job?.state,resultDeliveryState:result?.status,lastStage:job?.lastStage,lastStageDetail:bounded(job?.lastStageDetail),leaseExpiresAt:job?.leaseExpiresAt,lastHeartbeat:job?.lastHeartbeatAt,lastHeartbeatAgeMs:heartbeatAge,browserJobAttempts:job?.attempts,matchingBrowserJobCount:matches.length,sourceStatus:this.sourceStatus(job),contentScriptStatus:this.contentStatus(job),updatedAt:job?.updatedAt??record.updatedAt};})),observations};
    const token=await this.store.token();if(token&&this.bridge.publishBrowserSupervisorDiagnostics)try{await this.bridge.publishBrowserSupervisorDiagnostics(snapshot,token)}catch{}
  }
}
